#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
"""Generate a Netgen setup file that states the RM_IHPSG13 pin correspondence.

The layout view Magic extracts from the macro LEF and the vendor CDL
spell the same pin differently -- 'A_DIN[63]' versus 'A_DIN<63>', and
'VDD' versus 'VDD!' -- and netgen 1.5.272 has no directive that equates
either spelling. What it does have (::netgen::help) is

    equate classes <cellname1> [<pins>] <cellname2> [<pins>]

which takes the correspondence as two ORDERED lists. That is the honest
form: unlike 'equate pins', which matches two pin lists by position and
would be catastrophically wrong here (the CDL declares the 2048x64's 355
pins in a different order from the LEF and exactly 1 of 355 positions
agrees), this file writes down every pair, and the pairing is derived by
NAME, mechanically, and is auditable line by line.

The layout list is read from the run's extracted SPICE. The schematic
list is that same list transformed by '[n]' -> '<n>' and, for the three
supplies, 'VDD' -> 'VDD!'. Every transformed name is then CHECKED to
exist in the vendor CDL's own .SUBCKT line, and the two sets are checked
to be the same size, so a name this script invents rather than finds is
an error rather than a silent wrong pairing.

    usage: gen_netgen_setup.py <extracted.spice> <out.tcl> <cdl> [<cdl> ...]
"""
import os
import sys


def subckt_pins(path, name):
    lines = []
    for line in open(path, errors="replace"):
        line = line.rstrip("\n")
        if line.startswith("+") and lines:
            lines[-1] += " " + line[1:]
        else:
            lines.append(line)
    for line in lines:
        t = line.split()
        if len(t) > 1 and t[0].lower() == ".subckt" and t[1] == name:
            return t[2:]
    return None


def to_schematic(pin):
    if pin in ("VDD", "VSS", "VDDARRAY"):
        return pin + "!"
    return pin.replace("[", "<").replace("]", ">")


spice, out = sys.argv[1], sys.argv[2]
cdls = sys.argv[3:]

pdk_setup = os.environ.get(
    "PDK_NETGEN_SETUP",
    os.path.join(os.environ["PDK_ROOT"], "ihp-sg13g2",
                 "libs.tech", "netgen", "ihp-sg13g2_setup.tcl"))

with open(out, "w") as f:
    print(f"# generated by {os.path.basename(__file__)} -- do not hand-edit", file=f)
    print(f"source {pdk_setup}", file=f)
    for cdl in cdls:
        name = os.path.basename(cdl).split(".")[0]
        lay = subckt_pins(spice, name)
        sch = subckt_pins(cdl, name)
        assert lay is not None, f"{name} not found in {spice}"
        assert sch is not None, f"{name} not found in {cdl}"
        mapped = [to_schematic(p) for p in lay]
        assert len(lay) == len(sch), f"{name}: {len(lay)} layout pins vs {len(sch)} CDL pins"
        missing = sorted(set(mapped) - set(sch))
        assert not missing, f"{name}: names this script invented, not in the CDL: {missing[:8]}"
        assert set(mapped) == set(sch), f"{name}: CDL has pins the layout does not"
        print(f'# {name}: {len(lay)} pins, paired by name', file=f)
        print(f'if {{[lsearch $cells1 "{name}"] >= 0 && [lsearch $cells2 "{name}"] >= 0}} {{', file=f)
        print(f'    equate classes "-circuit1 {name}" {{{" ".join(lay)}}} \\', file=f)
        print(f'                   "-circuit2 {name}" {{{" ".join(mapped)}}}', file=f)
        print(f'    puts stdout "RM_IHPSG13 setup: equated {len(lay)} pins of {name}"', file=f)
        print("}", file=f)
print(f"wrote {out}")
