// SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
// SPDX-License-Identifier: CERN-OHL-W-2.0
`default_nettype none
// Actual decoded peer FC -> transmit credit reservation -> replay connection.
// local_init_done_i is supplied by the future receive-credit advertiser; never
// tied high internally. No receive buffers/advertisements, PHY or SoC instance.
module soc_pcie_flow_packets #(
    parameter [15:0] VENDOR_ID=16'hffff,DEVICE_ID=16'h0000,
    parameter integer APB_TIMEOUT=256,MAX_TLP_DWORDS=8,
    parameter integer REPLAY_DEPTH=4,REPLAY_TIMEOUT_CYCLES=1024,MAX_REPLAYS=3
) (
    input wire clk_i,rst_ni,link_up_i,training_i,retrain_done_i,local_init_done_i,
    output wire initialized_o,peer_init1_done_o,peer_init2_seen_o,credit_error_o,
    output wire [23:0] credit_header_limit_o,credit_header_consumed_o,
    output wire [35:0] credit_data_limit_o,credit_data_consumed_o,
    output wire [5:0] credit_infinite_o,
    input wire [15:0] function_id_i,
    input wire [7:0] rx_data_i,
    input wire rx_sop_i,rx_eop_i,rx_error_i,rx_valid_i,rx_dllp_i,
    output wire rx_ready_o,
    output wire [11:0] rx_expected_sequence_o,tx_next_sequence_o,
    output wire packet_accepted_o,packet_duplicate_o,packet_rejected_o,rx_tlp_seen_o,
    output wire [7:0] tx_data_o,
    output wire tx_sop_o,tx_eop_o,tx_valid_o,tx_dllp_o,tx_replay_o,
    input wire tx_ready_i,
    output wire fc_valid_o,
    output wire [1:0] fc_phase_o,fc_class_o,
    output wire [7:0] fc_header_o,
    output wire [11:0] fc_data_o,
    output wire bad_dllp_o,unsupported_dllp_o,
    output wire reserve_valid_o,
    output wire reserve_ready_o,
    output wire [1:0] reserve_class_o,
    output wire [10:0] reserve_payload_dw_o,
    output wire reserve_replay_o,
    output wire [4:0] buffered_o,outstanding_o,
    output wire [11:0] acknowledged_sequence_o,
    output wire replay_started_o,timeout_o,protocol_error_o,retry_exhausted_o,source_error_o,retrain_request_o,
    output wire psel_o,penable_o,
    output wire [11:0] paddr_o,
    output wire pwrite_o,
    output wire [3:0] pstrb_o,
    output wire [31:0] pwdata_o,
    input wire pready_i,pslverr_i,
    input wire [31:0] prdata_i,
    output wire error_o,memory_enable_o,
    output wire [31:0] bar0_o
);
    wire endpoint_error;
    soc_pcie_reliable_packets #(.VENDOR_ID(VENDOR_ID),.DEVICE_ID(DEVICE_ID),
        .APB_TIMEOUT(APB_TIMEOUT),.MAX_TLP_DWORDS(MAX_TLP_DWORDS),
        .REPLAY_DEPTH(REPLAY_DEPTH),.REPLAY_TIMEOUT_CYCLES(REPLAY_TIMEOUT_CYCLES),
        .MAX_REPLAYS(MAX_REPLAYS)) packets(
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .link_up_i(link_up_i),
        .training_i(training_i),
        .retrain_done_i(retrain_done_i),
        .function_id_i(function_id_i),
        .rx_data_i(rx_data_i),
        .rx_sop_i(rx_sop_i),
        .rx_eop_i(rx_eop_i),
        .rx_error_i(rx_error_i),
        .rx_valid_i(rx_valid_i),
        .rx_dllp_i(rx_dllp_i),
        .rx_ready_o(rx_ready_o),
        .rx_expected_sequence_o(rx_expected_sequence_o),
        .tx_next_sequence_o(tx_next_sequence_o),
        .packet_accepted_o(packet_accepted_o),
        .packet_duplicate_o(packet_duplicate_o),
        .packet_rejected_o(packet_rejected_o),
        .rx_tlp_seen_o(rx_tlp_seen_o),
        .tx_data_o(tx_data_o),
        .tx_sop_o(tx_sop_o),
        .tx_eop_o(tx_eop_o),
        .tx_valid_o(tx_valid_o),
        .tx_dllp_o(tx_dllp_o),
        .tx_replay_o(tx_replay_o),
        .tx_ready_i(tx_ready_i),
        .fc_valid_o(fc_valid_o),
        .fc_phase_o(fc_phase_o),
        .fc_class_o(fc_class_o),
        .fc_header_o(fc_header_o),
        .fc_data_o(fc_data_o),
        .bad_dllp_o(bad_dllp_o),
        .unsupported_dllp_o(unsupported_dllp_o),
        .reserve_valid_o(reserve_valid_o),
        .reserve_ready_i(reserve_ready_o),
        .reserve_class_o(reserve_class_o),
        .reserve_payload_dw_o(reserve_payload_dw_o),
        .reserve_replay_o(reserve_replay_o),
        .buffered_o(buffered_o),
        .outstanding_o(outstanding_o),
        .acknowledged_sequence_o(acknowledged_sequence_o),
        .replay_started_o(replay_started_o),
        .timeout_o(timeout_o),
        .protocol_error_o(protocol_error_o),
        .retry_exhausted_o(retry_exhausted_o),
        .source_error_o(source_error_o),
        .retrain_request_o(retrain_request_o),
        .psel_o(psel_o),
        .penable_o(penable_o),
        .paddr_o(paddr_o),
        .pwrite_o(pwrite_o),
        .pstrb_o(pstrb_o),
        .pwdata_o(pwdata_o),
        .pready_i(pready_i),
        .pslverr_i(pslverr_i),
        .prdata_i(prdata_i),
        .error_o(endpoint_error),
        .memory_enable_o(memory_enable_o),
        .bar0_o(bar0_o));
    soc_pcie_credit_tx credits(
        .clk_i(clk_i),.rst_ni(rst_ni),.link_up_i(link_up_i),
        .local_init_done_i(local_init_done_i),.rx_tlp_seen_i(rx_tlp_seen_o),
        .fc_valid_i(fc_valid_o),.fc_phase_i(fc_phase_o),.fc_class_i(fc_class_o),
        .fc_header_i(fc_header_o),.fc_data_i(fc_data_o),
        .reserve_valid_i(reserve_valid_o),.reserve_ready_o(reserve_ready_o),
        .reserve_class_i(reserve_class_o),.reserve_payload_dw_i(reserve_payload_dw_o),
        .reserve_replay_i(reserve_replay_o),.initialized_o(initialized_o),
        .peer_init1_done_o(peer_init1_done_o),.peer_init2_seen_o(peer_init2_seen_o),
        .protocol_error_o(credit_error_o),.header_limit_o(credit_header_limit_o),
        .header_consumed_o(credit_header_consumed_o),.data_limit_o(credit_data_limit_o),
        .data_consumed_o(credit_data_consumed_o),.infinite_o(credit_infinite_o));
    assign error_o=endpoint_error || credit_error_o || protocol_error_o || source_error_o;
endmodule
`default_nettype wire
