#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

"""Pin a harden to an exact set of RTL blobs instead of to the live tree.

Why this exists. On 2026-08-26 at 07:15:28 a concurrent session wrote a
half-finished `hw/rtl/lif_core.v` -- four wires driven by ECC logic that
was not there yet -- while a LibreLane run was between its lint step
(07:15:10, clean) and its synthesis step (07:15:35, four undriven
wires). The run aborted at Checker.YosysSynthChecks. Lint and synthesis
are separate processes reading the same path, so a config that names
`hw/rtl` has a window on every run where the sources can change under
it, and the run directory records no evidence of which version it read.

This script closes the window: it materialises a named git commit's
`hw/rtl` into a scratch directory, rewrites a config to read from there
with absolute paths, and prints the blob of every file it wrote. The
snapshot is disposable -- it is fully regenerable from the commit -- and
the printed blob table is what docs/20 quotes, per the docs/18
precedent that a run must be able to name the source it consumed.

Usage:
    ./pin_rtl.py <commit-ish> <base-config.json> <dest-dir>

Then:
    CONFIG=<dest-dir>/config.json <run script> --run-tag <tag> \\
        --force-run-dir <dest-dir>/run
"""

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))


def git(*args):
    return subprocess.run(
        ["git"] + list(args), cwd=REPO, capture_output=True, check=True
    ).stdout


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        return 1
    commit, base_config, dest = sys.argv[1], os.path.abspath(sys.argv[2]), os.path.abspath(sys.argv[3])
    rtl = os.path.join(dest, "rtl")
    os.makedirs(rtl, exist_ok=True)

    names = [
        line.split("/")[-1]
        for line in git("ls-tree", "--name-only", f"{commit}:hw/rtl").decode().split()
    ]
    print(f"pinned to {commit} ({git('rev-parse', commit).decode().strip()[:12]})")
    for n in names:
        blob = git("rev-parse", f"{commit}:hw/rtl/{n}").decode().strip()
        with open(os.path.join(rtl, n), "wb") as f:
            f.write(git("cat-file", "blob", blob))
        print(f"  {blob}  hw/rtl/{n}")

    # object_pairs_hook=list is needed at the TOP level, because a config
    # carries duplicate `//` comment keys that a dict would collapse. It
    # applies at EVERY nesting level though, so a nested object -- what
    # LAYERS_RC, VIAS_R, TECH_LEFS and MACROS are -- came back as a list
    # of pairs and re-serialised as a JSON array, producing a config the
    # flow cannot read. docs/25 open item 2; the second load is the fix,
    # and it is a second load rather than a cleverer hook because the two
    # requirements are genuinely opposed: keep duplicates at the top,
    # keep objects below it.
    pairs = json.load(open(base_config), object_pairs_hook=list)
    nested = json.load(open(base_config))
    base_dir = os.path.dirname(base_config)
    out = []
    for k, v in pairs:
        if k == "VERILOG_FILES":
            v = [os.path.join(rtl, os.path.basename(x.split("::", 1)[1])) for x in v]
        elif k == "VERILOG_INCLUDE_DIRS":
            v = [rtl]
        elif isinstance(v, list) and isinstance(nested.get(k), dict):
            v = nested[k]          # a nested object, not an array
        elif isinstance(v, str) and v.startswith("dir::"):
            # Any other dir:: path -- the pin-frame DEF template above all --
            # has to be absolutised too, because the config no longer lives
            # in the directory those paths were written relative to.
            v = os.path.abspath(os.path.join(base_dir, v.split("::", 1)[1]))
        out.append((k, v))
    out.append(
        (
            "//pinned",
            f"GENERATED by pin_rtl.py from {base_config} against RTL at {commit}. "
            "Sources are a disposable snapshot; regenerate rather than edit.",
        )
    )
    path = os.path.join(dest, "config.json")
    with open(path, "w") as f:
        f.write(
            "{\n"
            + ",\n".join(f"  {json.dumps(k)}: {json.dumps(v)}" for k, v in out)
            + "\n}\n"
        )
    print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
