from pathlib import Path
import ast,hashlib,json,difflib
R=Path.cwd();B=Path(__file__).resolve().parent
pin=lambda p:dict(bytes=Path(p).stat().st_size,sha256=hashlib.sha256(Path(p).read_bytes()).hexdigest())
old=B/'source-freeze01.json';j=json.loads(old.read_text());j['previous_freeze']=dict(path=str(old),**pin(old))
extra=['hw/soc/rtl/pcie/soc_pcie_gen3_continuous_rx_integrity_v23.v','hw/soc/rtl/pcie/soc_pcie_gen3_ingress_integrity_v11.v','hw/soc/rtl/pcie/soc_pcie_gen3_data_descrambler.v','hw/soc/rtl/pcie/soc_pcie_gen3_ingress.v','scripts/check_pcie_integrity.py','scripts/check_pcie_integrity_native.py','scripts/cocotb_results.py','scripts/generate_pcie_integrity_ingress_v11.py','hw/soc/tb/cocotb/Makefile.soc_pcie_gen3_continuous_rx_integrity_v23','scripts/check_pcie_gen3_continuous_rx_integrity_v23.py','hw/soc/tb/cocotb/test_soc_pcie_gen3_continuous_rx_integrity_v23.py','.venv/bin/python','.venv/pyvenv.cfg','hw/soc/tools/cocotb-venv/bin/python','hw/soc/tools/cocotb-venv/bin/cocotb-config','hw/soc/tools/cocotb-venv/pyvenv.cfg']
for name in extra:j['sources'][str(R/name)]=pin(R/name)
# Actual Makefile fallback uses this existing lexical cocotb venv. Freeze all
# executable/source/shared-object runtime files, excluding generated bytecode.
for root in (R/'hw/soc/tools/cocotb-venv/lib/python3.12/site-packages/cocotb',R/'hw/soc/tools/cocotb-venv/lib/python3.12/site-packages/cocotb_tools'):
 assert root.is_dir()
 for p in root.rglob('*'):
  if p.is_file()and'__pycache__'not in p.parts and p.suffix!='.pyc':j['sources'][str(p)]=pin(p)
j['runtime_scope']='Pinned selected lexical Python/cfg, wrappers/native Icarus runtime and actual cocotb fallback package/tools/makefiles/shared objects; base OS/stdlib are not hermetically vendored.'
f=B/'source-freeze02.json';assert not f.exists();f.write_text(json.dumps(j,indent=2)+'\n')
s=(B/'launch_controls01.py').read_text().replace('source-freeze01.json','source-freeze02.json').replace(pin(old)['sha256'],pin(f)['sha256']).replace('source-only-peer-vco01.json','source-only-peer-vco02.json')
p=B/'launch_controls02.py';assert not p.exists();p.write_text(s);ast.parse(s)
d=(B/'detach_controls01.py').read_text().replace('launch_controls01.py','launch_controls02.py').replace(repr(pin(B/'launch_controls01.py')),repr(pin(p))).replace('source-freeze01.json','source-freeze02.json').replace(repr(pin(old)),repr(pin(f))).replace('source-only-peer-vco01.json','source-only-peer-vco02.json')
q=B/'detach_controls02.py';assert not q.exists();q.write_text(d);ast.parse(d)
bridge=dict(reason='Additive dependency closure after independent source peer finding; all10product source bytes unchanged. No controls launched.',previous_freeze=pin(old),freeze=pin(f),products=j['product_sources'],sources=len(j['sources']),support={name:dict(parent_pin=pin(B/parent),candidate_pin=pin(B/name),whole_diff=''.join(difflib.unified_diff((B/parent).read_text().splitlines(True),(B/name).read_text().splitlines(True))))for name,parent in [('launch_controls02.py','launch_controls01.py'),('detach_controls02.py','detach_controls01.py')]})
(B/'source-bridges02.json').write_text(json.dumps(bridge,indent=2)+'\n')
print('freeze',pin(f),'sources',len(j['sources']));print('launcher',pin(p));print('detacher',pin(q))
