#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
"""Generate banked CAN byte offsets and bind only prepared upstream copies.

The pinned core implements the SJA1000 byte ABI. Every replaced literal is
checked against that immutable ABI before emitting named local parameters.
Register-read aliases and full-width write/FIFO/side-effect decodes are kept.
"""
import argparse
from pathlib import Path
import re

from generate_peripherals import UniqueLoader
import yaml

ROOT = Path(__file__).resolve().parents[1]
EXPECTED = {
    'COMMON': {'MODE', 'COMMAND', 'STATUS', 'IRQ', 'BTR0', 'BTR1', 'CDR'},
    'BASIC_RESET': {'ACR0', 'AMR0'},
    'BASIC_TX': {f'DATA{i}' for i in range(10)},
    'BASIC_RX': {f'DATA{i}' for i in range(10)},
    'EXTENDED': {'IER', 'ALC', 'ECC', 'EWL', 'RXERR', 'TXERR', 'RMC'},
    'EXTENDED_RESET': {f'{prefix}{i}' for prefix in ('ACR', 'AMR') for i in range(4)},
    'EXTENDED_TX': {f'DATA{i}' for i in range(13)},
    'EXTENDED_RX': {f'DATA{i}' for i in range(13)},
}


def load(path=ROOT / 'regmap/can.yaml'):
    spec = yaml.load(path.read_text(), Loader=UniqueLoader)
    if not isinstance(spec, dict) or set(spec) != {
            'schema', 'block', 'address_bits', 'register_read_bits', 'banks'}:
        raise ValueError('Invalid CAN map schema')
    for key, value in [('schema', 1), ('address_bits', 8), ('register_read_bits', 5)]:
        if type(spec[key]) is not int or spec[key] != value:
            raise ValueError('Unsupported CAN ' + key)
    if spec['block'] != 'can' or not isinstance(spec['banks'], dict) or set(spec['banks']) != set(EXPECTED):
        raise ValueError('Invalid CAN banks')
    for bank, expected in EXPECTED.items():
        regs = spec['banks'][bank]
        if not isinstance(regs, dict) or set(regs) != expected:
            raise ValueError('Invalid CAN bank members: ' + bank)
        if any(type(v) is not int or not 0 <= v < 32 for v in regs.values()):
            raise ValueError('Invalid CAN byte offset: ' + bank)
        if len(set(regs.values())) != len(regs):
            raise ValueError('Duplicate address within CAN bank: ' + bank)
    return spec


def values(spec):
    return {bank + '_' + name: offset for bank, regs in spec['banks'].items()
            for name, offset in regs.items()}


def outputs(spec):
    c = ['// SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut',
         '// SPDX-' + 'License-Identifier: Apache-2.0',
         '// Generated by regmap/generate_can.py from regmap/can.yaml.',
         '#ifndef SOC_CAN_REGS_H', '#define SOC_CAN_REGS_H', '']
    py = ['# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut',
          '# SPDX-' + 'License-Identifier: Apache-2.0',
          '# Generated by regmap/generate_can.py from regmap/can.yaml.', '']
    for bank, regs in spec['banks'].items():
        for name, offset in regs.items():
            c.append(f'#define SOC_CAN_{bank}_{name}_OFF 0x{offset:02X}u')
        c.append('')
        py.append('CAN_' + bank + ' = ' + repr(regs))
    c.append('#endif /* SOC_CAN_REGS_H */')
    return {'hw/soc/tb/sw/soc_can_regs.h': '\n'.join(c) + '\n',
            'sw/golden/can_regs_gen.py': '\n'.join(py) + '\n'}


def adapt(source_name, text, spec):
    """Return a named-constant copy; reject upstream or ABI drift atomically.

    Declarations contain only constants actually used by that module. A
    round-trip check reconstructs the exact original bytes independently of
    the added declarations; each original literal's width/value is checked.
    """
    if source_name not in ('can_registers.v', 'can_top.v', 'can_fifo.v'):
        return text
    original = text
    numbers = values(spec)
    used = set()
    replacements = []

    def symbol(key, width, old):
        if int(old) != numbers[key]:
            raise ValueError(f'Pinned CAN ABI mismatch: {key}: {old} != {numbers[key]}')
        used.add(key)
        name = 'NSSOC_CAN_' + key
        return name if width == 8 else name + f'[{width - 1}:0]'

    def patch(old, new):
        nonlocal text
        if text.count(old) != 1 or old == new:
            raise ValueError('Missing/ambiguous CAN binding: ' + old[:90])
        text = text.replace(old, new)
        replacements.append((old, new))

    if source_name == 'can_registers.v':
        bindings = {
            'we_mode': ['COMMON_MODE'], 'we_command': ['COMMON_COMMAND'],
            'we_bus_timing_0': ['COMMON_BTR0'], 'we_bus_timing_1': ['COMMON_BTR1'],
            'we_clock_divider_low': ['COMMON_CDR'], 'read_irq_reg': ['COMMON_IRQ'],
            'read_arbitration_lost_capture_reg': ['EXTENDED_ALC'],
            'read_error_code_capture_reg': ['EXTENDED_ECC'],
            'we_acceptance_code_0': ['BASIC_RESET_ACR0', 'EXTENDED_RESET_ACR0'],
            'we_acceptance_mask_0': ['BASIC_RESET_AMR0', 'EXTENDED_RESET_AMR0'],
            'we_interrupt_enable': ['EXTENDED_IER'],
            'we_error_warning_limit': ['EXTENDED_EWL'],
            'we_rx_err_cnt': ['EXTENDED_RXERR'], 'we_tx_err_cnt': ['EXTENDED_TXERR'],
        }
        for i in range(13):
            bindings[f'we_tx_data_{i}'] = ([f'BASIC_TX_DATA{i}'] if i < 10 else []) + [f'EXTENDED_TX_DATA{i}']
        for i in range(1, 4):
            bindings[f'we_acceptance_code_{i}'] = [f'EXTENDED_RESET_ACR{i}']
            bindings[f'we_acceptance_mask_{i}'] = [f'EXTENDED_RESET_AMR{i}']
        for wire, keys in bindings.items():
            lines = re.findall(r'(?m)^(?:wire\s+|assign\s+)' + wire + r'\s*=.*;$', text)
            if len(lines) != 1: raise ValueError('CAN decoder binding missing: ' + wire)
            line = lines[0]
            literals = list(re.finditer(r"8'd(\d+)", line))
            if len(literals) != len(keys): raise ValueError('CAN decoder arity changed: ' + wire)
            changed = line
            for match, key in reversed(list(zip(literals, keys))):
                changed = changed[:match.start()] + symbol(key, 8, match[1]) + changed[match.end():]
            patch(line, changed)
        read_banks = {0: ['COMMON', 'BASIC_RESET', 'BASIC_TX'],
                      1: ['COMMON', 'EXTENDED', 'EXTENDED_RESET', 'EXTENDED_TX']}
        cases = list(re.finditer(r"\{1'h([01]), 5'd(\d+)\}(\s*:)", text))
        if len(cases) != 46: raise ValueError('CAN read-case inventory changed')
        for case in cases:
            mode, offset = int(case[1]), int(case[2])
            key = next((bank + '_' + name for bank in read_banks[mode]
                        for name, value in spec['banks'][bank].items() if value == offset), None)
            if key is None: raise ValueError('Unbound CAN read case')
            changed = "{1'h" + case[1] + ', ' + symbol(key, 5, case[2]) + '}' + case[3]
            patch(case[0], changed)
    elif source_name == 'can_top.v':
        pairs = [('EXTENDED_RX_DATA0', '16'), ('EXTENDED_RX_DATA12', '28'),
                 ('BASIC_RX_DATA0', '20'), ('BASIC_RX_DATA9', '29')]
        for key, number in pairs:
            operator = '>=' if key.endswith('DATA0') else '<='
            old = f"addr {operator} 8'd{number}"
            patch(old, 'addr ' + operator + ' ' + symbol(key, 8, number))
    else:
        for key, number in [('EXTENDED_RX_DATA0', '16'), ('BASIC_RX_DATA0', '20')]:
            old = f"addr - 6'd{number}"
            patch(old, 'addr - ' + symbol(key, 6, number))
    # Full decoding width and every other source byte remain identical.
    restored = text
    for old, new in reversed(replacements):
        if restored.count(new) != 1: raise ValueError('Ambiguous inverse CAN binding')
        restored = restored.replace(new, old)
    if restored != original: raise ValueError('CAN adaptation changed unrelated bytes')
    header = re.search(r'\bmodule\s+' + source_name[:-2] + r'\s*\(.*?\);', text, re.S)
    if header is None: raise ValueError('CAN module header changed')
    declarations = '\n// Generated CAN byte-bank bindings; upstream logic is unchanged.\n'
    declarations += ''.join(f"localparam [7:0] NSSOC_CAN_{key} = 8'd{numbers[key]};\n" for key in sorted(used))
    return text[:header.end()] + '\n' + declarations + text[header.end():]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, data in outputs(load()).items():
        path = ROOT / name
        if not path.exists() or path.read_text() != data:
            stale.append(name)
            if not args.check: path.write_text(data)
    if stale and args.check: parser.exit(1, 'Stale CAN bindings: ' + ', '.join(stale) + '\n')
    print('CAN byte-bank bindings synchronized')


if __name__ == '__main__':
    main()
