"""Finite source/evidence delivery; measured failures remain explicit."""
from pathlib import Path
import datetime,hashlib,json
R=Path.cwd();B=Path(__file__).resolve().parent;A=B.parent/'pcie-integrity-v16-20261005';V15=B.parent/'pcie-integrity-v15-20261005'
def pin(p):
 with p.open('rb') as f:return dict(bytes=p.stat().st_size,sha256=hashlib.file_digest(f,'sha256').hexdigest())
def released(name):
 p=B/name;r=json.loads(p.read_text());assert r['status']=='PASS_IMMUTABLE_RELEASE_ROUNDTRIPS'
 assert len(r['assets'])==4 and all(a['authenticated_roundtrip'] and a['anonymous_roundtrip'] for a in r['assets'])
 for f in r['files']:assert pin(Path(f['path']))=={k:f[k] for k in ['bytes','sha256']}
 return r
native_release=released('release01.json');previous_release=released('predecessor-release02.json')
for base in [B,A,V15]:
 freeze=json.loads((base/'source-freeze.json').read_text())
 for n,v in freeze['files'].items():assert pin(R/n)==v
# Priorready immutable; these are distinct finite units, not one combined PASS.
p15=V15/'ready-finite.json';old=json.loads(p15.read_text());assert old['status']=='READY_REJECTED_V15_FRONTEND_RESOURCE_FAILURE'
notes=B/'predecessor-publication-preparation-note.json';notes.write_text(json.dumps(dict(status='PREPARATION_ERROR_RETAINED_NO_REMOTE_MUTATION',scope='First alias preparation mistakenly treated source_allowlist list asdict and failed beforemaking aliases. First CLI thenrefused missinginputfile beforepublication. Originalpredecessor-release01.log retained; preparationcorrected and freshpredecessor-release02 actual4asset publicationPASS. No source/native/test rerun.'),indent=2)+'\n')
files={}
for p in B.rglob('*'):
 if p.is_file() and not p.is_symlink() and '__pycache__' not in p.parts and p.name not in ['active-checkpoint.json','ready-finite.json']:
  files[str(p.relative_to(R))]=pin(p)
freeze=json.loads((B/'source-freeze.json').read_text());timing=json.loads((B/'timing-comparison.json').read_text());depth=json.loads((B/'native-read-depth-comparison.json').read_text())
r=dict(status='READY_V17_MEASURED_GAIN_RESIDUAL_SETUP_NOT_ADOPTED',utc=datetime.datetime.now(datetime.UTC).isoformat(),source_allowlist=[dict(repository_path=n,**v) for n,v in freeze['files'].items()],controls=dict(pytest_executions=39,distinct_predicates=38,positive_public_cases=26,actual_RTL_mutants=30,randomized_literal_read_cases=12288,directed_fourstate_cases=59,isolated_event_cases=31,excluded_MAX4118_ids=2,skipped=0),source_peer=pin(B/'source-only-peer-rx.json'),lifecycle_peer=pin(B/'continuation-source-only-peer-root03.json'),native=dict(mapped_cells=100817,flops=9410,limit_bytes=2*1024**3,CPU6=True,profile_ns=4,all_groups=[x for x in timing['groups'] if x['stage']=='PREPLACEMENT_REPAIRED'],delta_vs_V11_ns=timing['delta_vs_v11'],read_pin_depth={k:v for k,v in depth['comparison'].items() if k.startswith('output')},import_cell_pin_bits=367008,actual_import_graph_mutants=6),candidate_decision=pin(B/'candidate-decision.json'),release=pin(B/'release01.json'),assets=native_release['assets'],predecessor_provenance_assets=previous_release['assets'],V15_prior_ready=dict(path=str(p15.relative_to(R)),**pin(p15)),evidence=files,stable_baseline='V11',adopted=False,physical_acceptance=False,scope='Exactoriginal4ns/SS/TT/FF preplacement yieldsSS−3.336283,TT−0.611557,FF+0.943533ns andpositiveholds. Improvements0.215728/0.147133/0.087128ns vsV11 at17039additionalcells; actualreaddepth31/32versusrejectedV14 62. Timing remainsopen. NoMAX4118/fullformal/mappedfunctionalreplay/place/CTS/route/extractedRC/wholechipLVS/PCIePHY/productionapproval. All failures/supersession/diagnostics preserved; no repeat ofcompletedcontrols/native. Nativearchive containsempty selfstdoutlog snapshot atcut; finalstdoutand explicitnative-archive-cut-note retained separately.')
(B/'ready-finite.json').write_text(json.dumps(r,indent=2)+'\n')
f16=json.loads((A/'source-freeze.json').read_text());r16=dict(status='READY_PRESERVED_SUPERSEDED_V16_INCOMPLETE',utc=datetime.datetime.now(datetime.UTC).isoformat(),source_allowlist=[dict(repository_path=n,**v) for n,v in f16['files'].items()],source_integration_warning='Historical sources are complete inpublishedcapsule. Do not addfrozenV16 pathologicalring128 test toactive broadCI collection withoutanexplicit historicaltest policy/location; V17providesequivalentcompletedcoverage. Sourcefileshere remainunchanged andunadopted.',source_peer=pin(A/'source-only-peer-rx.json'),full_controls_complete=False,native_map_started=False,source_status='SUPERSEDED_INCOMPLETE_NOT_ADOPTED',release=dict(path=str((B/'predecessor-release02.json').relative_to(R)),**pin(B/'predecessor-release02.json')),assets=previous_release['assets'],evidence={str((B/n).relative_to(R)):pin(B/n) for n in ['superseded-v16-validation.json','frontend-diagnostic-validation.json','V16-supersession-receipt02.json','V16-supersession-receipt03.json','supersession-identity-guards02.json','continuation-source-only-peer-root02.json','continuation-source-only-peer-root03.json','pcie-integrity-v16-incomplete-supersession-20261005.tar.xz','pcie-integrity-v16-incomplete-validation-20261005.json','pcie-integrity-v16-frontend-diagnostics-20261005.tar.xz','pcie-integrity-v16-frontend-validation-20261005.json','predecessor-release02.json']},adopted=False,physical_acceptance=False,scope='V16ring16/64literalcontrolspassed, ring128Icarus12/14compilerunfinished. Afterfull39V17+independentpeers, exactownedjobs author-superseded. OriginalV2teardownobservationrace retainedfailed; V3closedremainingprobe withstrictsignalguards. OriginalV16sources/partialbench/logs/CPUstats anddiagnosticcompleted4096case/31sensitivity+9mutant evidence allpreserved. NoV16fullsuite/native/timingPASS.')
(A/'ready-finite.json').write_text(json.dumps(r16,indent=2)+'\n')
print(json.dumps({'V17':pin(B/'ready-finite.json'),'V16':pin(A/'ready-finite.json'),'V15':pin(p15),'V17evidence_count':len(files),'V17sources':len(r['source_allowlist']),'unique_V17_V16_assets':len(native_release['assets'])+len(previous_release['assets'])},indent=2))
