from pathlib import Path
import ast,hashlib,json,difflib,xml.etree.ElementTree as ET
R=Path.cwd();B=Path(__file__).resolve().parent
def pin(p):b=Path(p).read_bytes();return dict(bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
f=json.loads((B/'source-freeze03.json').read_text());old=json.loads((B/'source-freeze02.json').read_text());changed=[]
for p,v in f['sources'].items():
 assert pin(R/p)==v;original=B/'pre-execution-source02'/p;assert pin(original)==old['sources'][p]
 if v!=old['sources'][p]:changed.append(p)
assert set(changed)=={'sw/tests/test_pcie_gen3_integrity_v22_miter.py','hw/soc/tb/cocotb/test_soc_pcie_gen3_continuous_rx_integrity_v22.py'}
mp='sw/tests/test_pcie_gen3_integrity_v22_miter.py';a=(B/'pre-execution-source02'/mp).read_text();b=(R/mp).read_text();before='end\nalways @(negedge clk_i) begin\n #0.002;';after=' // Observe completed NBAs on this actual fault edge, before Ports.cycle returns.\n #0.002;';assert a.count(before)==1 and a.replace(before,after)==b
bp='hw/soc/tb/cocotb/test_soc_pcie_gen3_continuous_rx_integrity_v22.py';a=(B/'pre-execution-source02'/bp).read_text();b=(R/bp).read_text();before='serial_words(wire_dllp(good) + token + bytes(2048))';after='serial_words(bytes(16) + wire_dllp(good) + token + bytes(2048))';assert a.count(before)==1 and a.replace(before,after)==b
# Unchanged original16caseprefix and public Ports.cycle active-edge timing read directly.
p=R/'hw/soc/tb/cocotb/test_soc_pcie_gen3_continuous_rx_integrity_v21.py';assert b.replace('_v22','_v21').replace('V22_','V21_').startswith(p.read_text());assert 'd.clk_i.value = 1\n        await Timer(2, unit="ns")' in b
l=json.loads((B/'launch-source-freeze03.json').read_text());assert l['freeze']==pin(B/'source-freeze03.json')
for n,v in l['support'].items():assert pin(B/n)==v
# Whole runner inverse, only output/version/freeze/test-list plus helperpin gate.
a=(B/'launch_controls02.py').read_text();b=(B/'launch_controls03.py').read_text();x=b.replace('source-freeze03','source-freeze02').replace('source-only-peer-vco03','source-only-peer-vco02').replace(pin(B/'source-freeze03.json')['sha256'],pin(B/'source-freeze02.json')['sha256']).replace('controls03','controls01').replace('controls-status03','controls-status01').replace('controls-owner03','controls-owner01');x=x.replace("assert j['targeted_helper']==pin(B/'targeted_controls03.py')\n",'');line=next(z for z in a.splitlines()if z.startswith('command='));x='\n'.join(line if z.startswith('command=')else z for z in x.splitlines())+'\n';assert x==a
# Controller selected9tests is exactly full miter file (excluding4118) plus strictchangedcase17.
target=(B/'targeted_controls03.py').read_text();assert "dict(passed=1,failed=0,skipped=16)"in target and "'V22_CACHE_QUARANTINE epochs=8'"in target
assert "'sw/tests/test_pcie_gen3_integrity_v22_miter.py',str(B/'targeted_controls03.py'),'-k','not 4118'" in b
# Read/recount old actual campaign XML, retaining allthreefailures.
cases=list(ET.parse(B/'controls01.xml').getroot().iter('testcase'));counts=dict(passed=sum(c.find('failure')is None and c.find('error')is None and c.find('skipped')is None for c in cases),failed=sum(c.find('failure')is not None or c.find('error')is not None for c in cases));assert counts==dict(passed=26,failed=3)
a=(B/'detach_controls02.py').read_text();b=(B/'detach_controls03.py').read_text();x=b.replace('source-freeze03','source-freeze02').replace('source-only-peer-vco03','source-only-peer-vco02').replace('launch_controls03','launch_controls02').replace('controls03','controls01').replace('controls-status03','controls-status01').replace('controls-detached-once03','controls-detached-once01').replace('controls-launch03','controls-launch01').replace('controls-detached-receipt03','controls-detached-receipt01').replace(str(pin(B/'source-freeze03.json')),str(pin(B/'source-freeze02.json'))).replace(str(pin(B/'launch_controls03.py')),str(pin(B/'launch_controls02.py')));assert x==a
r=dict(status='PASS_SOURCE_ONLY_V22_QUARANTINED_CACHE',freeze=pin(B/'source-freeze03.json'),targeted_helper=pin(B/'targeted_controls03.py'),findings=[],method=pin(__file__),previous_peer=pin(B/'source-only-peer-vco02.json'),support_freeze=pin(B/'launch-source-freeze03.json'),source_pins=f['sources'],preserved_actual_campaign=counts,old_actual_xml=pin(B/'controls01.xml'),changed_sources=changed,review=['Observer captures step/fault before currentposedge NBA, waits2ps inside same always block and samples after NBA. Ports.cycle reads at+2ns with clockstillhigh; formerly nextnegedge never occurred before that assertion. Fixed event alignment does not alter DUT or loosen any screen.','Additional16IDL bytes form one parser four-DWORD slice, advancing owned ring pointers before nextslice goodDLLP+malformedtoken. Thus retain-owner mutant has nonzero pointers and must trigger strict control/quarantine mismatch. Original all8 fault-cache-divergence epochs and fresh owner byte scoreboard unchanged.','All seven other product/test sources byteidentical; original16publiccase prefix exact. Full miterpositive17cases, all6actualmiter mutants, inverse and changed17thdirectcase willrerun. Compile or coverage errors cannot substitute semantic failures.','Entire launcher/detacher byte inverses preserve CPU6/2GiB ownership/cancellation/nohealthytimeout; only fresh03 outputs, exactfreeze/helper binding and9test selection change.'],metadata_qualification='Inherited sourcefreeze scope says nohardwarecontrols; interpret only newrevision03, as prior26PASS/3FAIL are actual andpreserved. No native mapping or03tests runyet.',native_or_control_execution_by_peer=False)
(B/'source-only-peer-vco03.json').write_text(json.dumps(r,indent=2)+'\n');print(r['status'],pin(B/'source-only-peer-vco03.json'))
