# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
SIM ?= icarus
TOPLEVEL_LANG = verilog
THIS_MK := $(lastword $(MAKEFILE_LIST))
VENV_BIN := $(abspath $(dir $(THIS_MK))/../../../.venv/bin)
ifeq ($(shell command -v cocotb-config 2>/dev/null),)
GOALS := $(if $(MAKECMDGOALS),$(MAKECMDGOALS),sim)
.PHONY: $(GOALS)
$(GOALS):
	@PATH="$(VENV_BIN):$$PATH" $(MAKE) -f $(THIS_MK) --no-print-directory $@
else
RTL = $(PWD)/../../rtl
VERILOG_SOURCES = $(RTL)/soc_eth.v $(RTL)/../gen/interfaces.bundle.vh
TOPLEVEL = soc_eth
MODULE = test_soc_eth
SIM_BUILD ?= sim_build_soc_eth
COCOTB_RESULTS_FILE ?= results_soc_eth.xml
export COCOTB_RESULTS_FILE
include $(shell cocotb-config --makefiles)/Makefile.sim
endif
