# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
SIM ?= icarus
TOPLEVEL_LANG = verilog
THIS_MK := $(lastword $(MAKEFILE_LIST))
VENV_BIN := $(abspath $(dir $(THIS_MK))/../../../.venv/bin)
ifeq ($(shell command -v cocotb-config 2>/dev/null),)
GOALS := $(if $(MAKECMDGOALS),$(MAKECMDGOALS),sim)
.PHONY: $(GOALS)
$(GOALS):
	@PATH="$(VENV_BIN):$$PATH" $(MAKE) -f $(THIS_MK) --no-print-directory $@
else
VERILOG_SOURCES = $(abspath ../../rtl/soc_uart.v)
TOPLEVEL = soc_uart
COCOTB_TEST_MODULES = test_soc_uart_rx
SIM_BUILD ?= sim_build_soc_uart_rx
COCOTB_RESULTS_FILE ?= results_soc_uart_rx.xml
export COCOTB_RESULTS_FILE
include $(shell cocotb-config --makefiles)/Makefile.sim
endif
