#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

"""Emit the flash images the QSPI testbenches load, and the C header the
bring-up program checks them against.

WHY THIS EXISTS. hw/soc/tb/flash_w25q128jv.v models a flash device;
what the device HOLDS has to come from somewhere that is neither the
RTL nor the program, so that a read through the controller is compared
against an expectation fixed before the simulation ran. This is the
same rule hw/soc/flow/gen_npu_vectors.py applies to the NPU's answer:
computed here, at build time, into constants.

Two images, one per chip select, each a byte-per-line $readmemh file:

  flash0.hex   [0x000000, PATTERN_BYTES)  a pseudo-random byte pattern,
                                           seed SEED0
               [WIMG_OFF, ...)              THE WEIGHT IMAGE: a 16-byte
                                           header and the docs/51 weight
                                           words, so that the NPU can be
                                           fed from where a flight part
                                           would feed it
  flash1.hex   [0x000000, PATTERN_BYTES)  the same pattern under SEED1,
                                           so that a read that reached
                                           the wrong device is visibly
                                           wrong

The weight image is the SAME weights gen_npu_vectors.py packs into the
ROM header (same generator, same seed, same packing), so the inference
the program runs from flash has the same golden answer as the one it
runs from ROM, and the two can be compared word for word.

The header, qspi_image.h, carries the offsets, the seeds, the weight
image's magic, count and checksum, and a table of sample words at
chosen addresses with their expected values -- expected values written
here, from the pattern, and not read back from anything. The program
compares RX against the table. It does not re-implement the pattern.

Run:  python3 hw/soc/flow/gen_flash_image.py <out_dir>
"""

import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "hw" / "soc" / "flow"))
sys.path.insert(0, str(ROOT / "sw"))

import gen_npu_vectors as npu                    # noqa: E402

PATTERN_BYTES = 0x8000
SEED0 = 0x00
SEED1 = 0xA5
WIMG_OFF = 0x10000
WIMG_MAGIC = 0x3157534E        # "NSW1" little-endian
IMAGE_BYTES = 1 << 17          # the model's MEM_BYTES

# Sample addresses for the program's checks: word aligned at the start,
# in the middle, at the top of the pattern, and one unaligned byte
# address, which the single-lane read must handle and the quad read is
# not asked to (datasheet table 9.6 note 6).
SAMPLE_ADDRS = [0x000000, 0x000004, 0x000100, 0x001234, 0x004000,
                0x007FFC, 0x000003]


def pattern_byte(addr, seed):
    """One byte of the pattern. Deterministic, not periodic over the
    region, and never the erased value everywhere: the xor of two
    multiplied address slices and a per-device seed."""
    a = addr & 0xFFFFFF
    return ((a * 0x9E) ^ (a >> 7) ^ ((a >> 15) * 0x5B) ^ seed) & 0xFF


def pattern_word(addr, seed):
    return sum(pattern_byte(addr + k, seed) << (8 * k) for k in range(4))


def weight_image():
    """The docs/51 weight words, from the same generator the ROM header
    uses, as a byte string with its header."""
    weights = npu.make_weights(npu.N_AXONS, npu.N_NEURONS)
    words = npu.pack_words(weights, npu.N_NEURONS)
    body = b"".join(struct.pack("<II", w & 0xFFFFFFFF, (w >> 32) & 0xFFFFFFFF)
                    for w in words)
    checksum = 0
    for (v,) in struct.iter_unpack("<I", body):
        checksum = (checksum + v) & 0xFFFFFFFF
    geom = (npu.N_AXONS << 16) | npu.N_NEURONS
    header = struct.pack("<IIII", WIMG_MAGIC, len(words), geom, checksum)
    return header + body, len(words), checksum, geom


def build_image(seed, with_weights):
    img = bytearray([0xFF] * IMAGE_BYTES)
    for a in range(PATTERN_BYTES):
        img[a] = pattern_byte(a, seed)
    wimg = None
    if with_weights:
        wimg, n, cs, geom = weight_image()
        img[WIMG_OFF:WIMG_OFF + len(wimg)] = wimg
    return img


def write_hex(path, img):
    with open(path, "w") as f:
        f.write("".join("%02x\n" % b for b in img))


def emit_header(out):
    wimg, n_words, checksum, geom = weight_image()
    L = []
    L.append("/* GENERATED by hw/soc/flow/gen_flash_image.py. Do not edit. */")
    L.append("/*")
    L.append(" * What the flash image on chip select 0 holds, and what a read of")
    L.append(" * it must return. The expected words are computed here from the")
    L.append(" * pattern and never read back from the simulation.")
    L.append(" */")
    L.append("#ifndef QSPI_IMAGE_H")
    L.append("#define QSPI_IMAGE_H")
    L.append("")
    L.append("#include <stdint.h>")
    L.append("")
    L.append(f"#define QSPI_IMG_PATTERN_BYTES 0x{PATTERN_BYTES:06X}u")
    L.append(f"#define QSPI_IMG_SEED0 0x{SEED0:02X}u")
    L.append(f"#define QSPI_IMG_SEED1 0x{SEED1:02X}u")
    L.append("")
    L.append("/* the weight image: header then N_WORDS x (lo, hi) */")
    L.append(f"#define QSPI_IMG_WIMG_OFF   0x{WIMG_OFF:06X}u")
    L.append(f"#define QSPI_IMG_WIMG_MAGIC 0x{WIMG_MAGIC:08X}u")
    L.append(f"#define QSPI_IMG_WIMG_WORDS {n_words}u")
    L.append(f"#define QSPI_IMG_WIMG_GEOM  0x{geom:08X}u")
    L.append(f"#define QSPI_IMG_WIMG_CSUM  0x{checksum:08X}u")
    L.append(f"#define QSPI_IMG_WIMG_BYTES {len(wimg)}u")
    L.append("")
    L.append("/* sample words: address, expected value on CS0, expected on CS1 */")
    L.append(f"#define QSPI_IMG_N_SAMPLES {len(SAMPLE_ADDRS)}")
    L.append("static const uint32_t qspi_img_sample_addr[QSPI_IMG_N_SAMPLES] = {")
    L.append("    " + ", ".join(f"0x{a:06X}u" for a in SAMPLE_ADDRS))
    L.append("};")
    L.append("static const uint32_t qspi_img_sample_cs0[QSPI_IMG_N_SAMPLES] = {")
    L.append("    " + ", ".join(f"0x{pattern_word(a, SEED0):08X}u"
                                for a in SAMPLE_ADDRS))
    L.append("};")
    L.append("static const uint32_t qspi_img_sample_cs1[QSPI_IMG_N_SAMPLES] = {")
    L.append("    " + ", ".join(f"0x{pattern_word(a, SEED1):08X}u"
                                for a in SAMPLE_ADDRS))
    L.append("};")
    L.append("")
    L.append("#endif /* QSPI_IMAGE_H */")
    L.append("")
    out.write_text("\n".join(L))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: gen_flash_image.py <out_dir>")
    d = Path(sys.argv[1])
    d.mkdir(parents=True, exist_ok=True)
    write_hex(d / "flash0.hex", build_image(SEED0, True))
    write_hex(d / "flash1.hex", build_image(SEED1, False))
    emit_header(d / "qspi_image.h")
    _, n, cs, _ = weight_image()
    print(f"wrote {d}/flash0.hex, flash1.hex, qspi_image.h "
          f"({PATTERN_BYTES} pattern bytes, {n} weight words at "
          f"0x{WIMG_OFF:06X}, checksum 0x{cs:08X})")
