#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
"""Build an ignored, reproducible dependency bundle; never edit upstream trees."""
import hashlib
import json
import re
import subprocess
from pathlib import Path

SOC = Path(__file__).resolve().parents[1]
PINS = {
    'verilog-i2c': 'a65be4045e898a52e791c6ee71f8f79a7cd2e129',
    'spacewire_reloaded': '450d2254bb980dc08825a575e205acbbefbc8a69',
    'can': '470f0e7ab174dfef01a05f5d5ad01f28f6f4dc17',
}


def main():
    for name, pin in PINS.items():
        path = SOC / 'ext' / name
        actual = subprocess.check_output(['git', '-C', str(path), 'rev-parse', 'HEAD'], text=True).strip()
        dirty = subprocess.check_output(['git', '-C', str(path), 'status', '--porcelain'], text=True)
        if actual != pin or dirty:
            raise SystemExit(f'{name}: expected clean {pin}; run make soc-interfaces-prepare')
    spw = SOC / 'ext/spacewire_reloaded/rtl/verilog'
    can = SOC / 'ext/can/rtl/verilog'
    sources = [SOC / 'ext/verilog-i2c/rtl/i2c_master.v']
    sources += [spw / (n + '.v') for n in (
        'syncdff', 'spwram', 'spwrecvfront_generic', 'spwrecvfront_fast',
        'spwrecv', 'spwxmit', 'spwxmit_fast', 'spwlink', 'spwstream')]
    sources += sorted(p for p in can.glob('*.v') if p.name != 'can_defines.v')
    hashes = {}

    def expand(path):
        data = path.read_text()
        hashes[str(path.relative_to(SOC))] = hashlib.sha256(path.read_bytes()).hexdigest()
        def include(match):
            name = match.group(1)
            candidates = [path.parent / name, SOC / 'ext/can/bench/verilog' / name]
            included = next((p for p in candidates if p.is_file()), None)
            if included is None:
                raise RuntimeError(f'unresolved include {path}: {name}')
            return expand(included)
        return re.sub(r'`include\s+"([^"\n]+)"', include, data)

    text = '// Generated by prepare_interfaces.py; upstream licences retained below.\n`ifndef YOSYS\n`begin_keywords "1364-2005"\n`endif\n`define CAN_WISHBONE_IF\n`default_nettype wire\n'
    for source in sources:
        text += '\n// Source: ' + str(source.relative_to(SOC)) + '\n' + expand(source) + '\n'
    dest = SOC / 'gen/interfaces.bundle.vh'
    dest.parent.mkdir(exist_ok=True)
    dest.write_text(text + '\n`ifndef YOSYS\n`end_keywords\n`endif\n`default_nettype wire\n')
    dest.with_suffix('.json').write_text(json.dumps({'pins': PINS, 'inputs': hashes,
        'bundle_sha256': hashlib.sha256(dest.read_bytes()).hexdigest()}, indent=2) + '\n')
    print(f'{dest}: {len(sources)} upstream RTL files, {len(hashes)} inputs')


if __name__ == '__main__':
    main()
