# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
"""Independent bounded source-only balanced read peer; no HDL/native execution."""
from pathlib import Path
import hashlib,json,runpy,datetime
B=Path(__file__).resolve().parent;R=B.parents[3]
def pin(p):
 b=Path(p).read_bytes();return dict(bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
f=B/'source-freeze.json';freeze=json.loads(f.read_text());assert pin(f)==dict(bytes=2009,sha256='5cbf5074df23efb6b713edd77425651e7612b5aa1ea458b9c8aa552cdb97b530')
for p,h in freeze['files'].items():assert pin(R/p)==h
G=runpy.run_path(str(R/'scripts/generate_pcie_integrity_read_v15.py'));old=G['SOURCE'];new=R/'hw/soc/rtl/pcie/soc_pcie_gen3_framer_rx_integrity_v15.v';assert pin(old)==freeze['baseline']
s=new.read_text();assert s==G['candidate']();assert s.count(G['balanced_read']())==1
assert s.replace(G['balanced_read'](),G['original_read']()).replace('integrity_v15','integrity_v11')==old.read_text()
assert sum(G['FIELDS'].values())==60
for name in ['hw/soc/rtl/pcie/soc_pcie_gen3_continuous_rx_integrity_v11.v','hw/soc/tb/cocotb/test_soc_pcie_gen3_continuous_rx_integrity_v11.py','hw/soc/tb/cocotb/Makefile.soc_pcie_gen3_continuous_rx_integrity_v11']:
 assert (R/name.replace('_v11','_v15')).read_text().replace('integrity_v15','integrity_v11')==(R/name).read_text()
record=dict(status='PASS_V15_BALANCED_READ_SOURCE_ONLY_PEER',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),source_freeze=pin(f),sources=freeze['files'],baseline=freeze['baseline'],reviewer='/root/rx_route_resume',method=pin(__file__),verified=['Generator output byte-equals frozen RTL; replacing only balanced read block and module version restores entire V11 framer exactly. Wrapper, cocotb serial oracle and Makefile inverse versions byte-equal V11. No writer, verdict cache, fault, pointer, epoch, commit or reset edits.','60-bit payload layout exactly matches data32/keep4/sop4/eop4/dllp4/sequence12. For each of four lanes, tree addresses cover an independent2N segment: unused index0 explicitly set, N leaves set, then N-1 internal nodes assigned bottom-up. Final maximum index8N-1 is within declared arrays.','Old masked read address is unchanged. Integer equality against constant slot plus procedural if turns unknown eligibility into known0; valid power-of-two ring guard remains inherited. At most one leaf eligible for each lane; unknown address yields no eligible leaf just as old dynamic-index predicate is not true.','Each internal flag is OR of known0/1 flags. Payload selection uses that known left flag and a mux, preserving literal selected X/Z. Zero or one eligible leaf induction yields zero or exact original payload; no duplicate contributions or payload OR conversion.','Final lane<count procedural gate preserves original unknown-count rejection; keep/verdict and unknown-count conjunction moves across only pure combinational logic with the same not-true masking. All output defaults remain zero.','Source controls compare literal old/new blocks for16/64/128 rings, all metadata and wrap; targeted59 X/Z/unknown/unselected cases plus actual payloadOR Z-conversion fault and10 select/tree mutants inspected. Full public miter still compares all named ports and occupied/committed metadata. Controls are authored evidence, not rerun or assumed complete by this peer.'],issues_found=[],native_or_HDL_executed=False,controls_rerun=False,timing_claim=False,qualified_rc=False,physical_acceptance=False,limitations=['Logarithmic RTL tree shape is not proof of emitted gate depth or timing benefit. Fresh emitted-cone inspection, same4ns physical timing and complete saved execution controls remain required.','No fullchip, complete Gen3 PCS/PHY or production acceptance.'])
p=B/'source-only-peer-rx.json';p.write_text(json.dumps(record,indent=2)+'\n');print(pin(p))
