###############################################################################
# Created by write_sdc
###############################################################################
current_design soc_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk_i -period 20.0000 [get_ports {clk_i}]
set_clock_transition 0.1500 [get_clocks {clk_i}]
set_clock_uncertainty 0.2500 clk_i
set_propagated_clock [get_clocks {clk_i}]
create_clock -name eth_rx_clk_i -period 8.0000 [get_ports {eth_rx_clk_i}]
set_clock_transition 0.1500 [get_clocks {eth_rx_clk_i}]
set_clock_uncertainty 0.2500 eth_rx_clk_i
set_propagated_clock [get_clocks {eth_rx_clk_i}]
create_clock -name eth_tx_clk_i -period 8.0000 [get_ports {eth_tx_clk_i}]
set_clock_transition 0.1500 [get_clocks {eth_tx_clk_i}]
set_clock_uncertainty 0.2500 eth_tx_clk_i
set_propagated_clock [get_clocks {eth_tx_clk_i}]
create_generated_clock -name eth_gtx -source [get_ports {eth_tx_clk_i}] -divide_by 1 [get_ports {eth_gtx_clk_o}]
set_clock_uncertainty 0.2500 eth_gtx
set_propagated_clock [get_clocks {eth_gtx}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {can_rx_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mdio_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_rx_clk_i}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rx_dv_i}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rx_dv_i}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rx_er_i}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rx_er_i}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[0]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[0]}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[1]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[1]}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[2]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[2]}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[3]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[3]}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[4]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[4]}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[5]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[5]}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[6]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[6]}]
set_input_delay 0.5000 -clock [get_clocks {eth_rx_clk_i}] -min -add_delay [get_ports {eth_rxd_i[7]}]
set_input_delay 3.0000 -clock [get_clocks {eth_rx_clk_i}] -max -add_delay [get_ports {eth_rxd_i[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_tx_clk_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_i[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {i2c_scl_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {i2c_sda_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {irq_external_i}]
set_input_delay 1.5000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_i[0]}]
set_input_delay 10.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_i[0]}]
set_input_delay 1.5000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_i[1]}]
set_input_delay 10.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_i[1]}]
set_input_delay 1.5000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_i[2]}]
set_input_delay 10.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_i[2]}]
set_input_delay 1.5000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_i[3]}]
set_input_delay 10.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_i[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {rst_ni}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spi_miso_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spw_di_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spw_si_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {strap_i[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {strap_i[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {strap_i[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {strap_i[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {uart_rx_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {wdog_dis_i}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {alert_major_bus_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {alert_major_internal_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {alert_minor_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {can_bus_off_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {can_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {can_tx_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {core_sleep_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {double_fault_seen_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_gtx_clk_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mbist_done_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mbist_done_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mbist_failed_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mbist_failed_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mdc_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mdio_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {eth_mdio_oe_o}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_tx_en_o}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_tx_en_o}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_tx_er_o}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_tx_er_o}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[0]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[0]}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[1]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[1]}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[2]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[2]}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[3]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[3]}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[4]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[4]}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[5]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[5]}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[6]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[6]}]
set_output_delay -0.5000 -clock [get_clocks {eth_gtx}] -min -add_delay [get_ports {eth_txd_o[7]}]
set_output_delay 2.5000 -clock [get_clocks {eth_gtx}] -max -add_delay [get_ports {eth_txd_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_o[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gpio_oe_o[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {gptimer_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {i2c_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {i2c_scl_oe_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {i2c_sda_oe_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {irq_soft_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {irq_timer_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_busy_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_done_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[32]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[33]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[34]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[35]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[36]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[37]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[38]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[39]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[40]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[41]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[42]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[43]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[44]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[45]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[46]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[47]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[48]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[49]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[50]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[51]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[52]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[53]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[54]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[55]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[56]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[57]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[58]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[59]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[60]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[61]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[62]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[63]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_actual_o[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_addr_o[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_background_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[32]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[33]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[34]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[35]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[36]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[37]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[38]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[39]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[40]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[41]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[42]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[43]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[44]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[45]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[46]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[47]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[48]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[49]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[50]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[51]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[52]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[53]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[54]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[55]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[56]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[57]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[58]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[59]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[60]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[61]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[62]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[63]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_expected_o[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_phase_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_phase_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_fail_phase_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mbist_failed_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {nmi_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {npu_aer_in_stb_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {npu_aer_out_vld_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {npu_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {npu_ser_cs_n_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {npu_ser_miso_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {npu_ser_mosi_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {npu_ser_sck_o}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_cs_no[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_cs_no[0]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_cs_no[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_cs_no[1]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_o[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_o[0]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_o[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_o[1]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_o[2]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_o[2]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_o[3]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_o[3]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_oe_o[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_oe_o[0]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_oe_o[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_oe_o[1]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_oe_o[2]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_oe_o[2]}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_io_oe_o[3]}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_io_oe_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {qspi_irq_o}]
set_output_delay -4.0000 -clock [get_clocks {clk_i}] -min -add_delay [get_ports {qspi_sck_o}]
set_output_delay 3.0000 -clock [get_clocks {clk_i}] -max -add_delay [get_ports {qspi_sck_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spi_cs_no[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spi_cs_no[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spi_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spi_mosi_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spi_sck_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spw_do_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spw_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {spw_so_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {uart_irq_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {uart_tx_o}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {wdog_no}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {wdog_rst_o}]
set_max_delay -ignore_clock_latency\
    -from [get_clocks {clk_i}]\
    -to [get_clocks {eth_rx_clk_i}] 8.0000
set_max_delay -ignore_clock_latency\
    -from [get_clocks {clk_i}]\
    -to [get_clocks {eth_tx_clk_i}] 8.0000
set_max_delay -ignore_clock_latency\
    -from [get_clocks {eth_rx_clk_i}]\
    -to [get_clocks {clk_i}] 8.0000
set_max_delay -ignore_clock_latency\
    -from [get_clocks {eth_rx_clk_i}]\
    -to [get_clocks {eth_tx_clk_i}] 8.0000
set_max_delay -ignore_clock_latency\
    -from [get_clocks {eth_tx_clk_i}]\
    -to [get_clocks {clk_i}] 8.0000
set_max_delay -ignore_clock_latency\
    -from [get_clocks {eth_tx_clk_i}]\
    -to [get_clocks {eth_rx_clk_i}] 8.0000
set_false_path -hold\
    -from [get_clocks {clk_i}]\
    -to [list [get_clocks {eth_rx_clk_i}]\
           [get_clocks {eth_tx_clk_i}]]
set_false_path -hold\
    -from [get_clocks {eth_rx_clk_i}]\
    -to [list [get_clocks {clk_i}]\
           [get_clocks {eth_tx_clk_i}]]
set_false_path -hold\
    -from [get_clocks {eth_tx_clk_i}]\
    -to [list [get_clocks {clk_i}]\
           [get_clocks {eth_rx_clk_i}]]
set_false_path\
    -from [get_ports {irq_external_i}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0060 [get_ports {can_bus_off_o}]
set_load -pin_load 0.0060 [get_ports {can_irq_o}]
set_load -pin_load 0.0060 [get_ports {can_tx_o}]
set_load -pin_load 0.0060 [get_ports {core_sleep_o}]
set_load -pin_load 0.0060 [get_ports {double_fault_seen_o}]
set_load -pin_load 0.0060 [get_ports {eth_irq_o}]
set_load -pin_load 0.0060 [get_ports {eth_mdc_o}]
set_load -pin_load 0.0060 [get_ports {eth_mdio_o}]
set_load -pin_load 0.0060 [get_ports {eth_mdio_oe_o}]
set_load -pin_load 0.0060 [get_ports {eth_gtx_clk_o}]
set_load -pin_load 0.0060 [get_ports {eth_tx_en_o}]
set_load -pin_load 0.0060 [get_ports {eth_tx_er_o}]
set_load -pin_load 0.0060 [get_ports {gpio_irq_o}]
set_load -pin_load 0.0060 [get_ports {gptimer_irq_o}]
set_load -pin_load 0.0060 [get_ports {i2c_irq_o}]
set_load -pin_load 0.0060 [get_ports {i2c_scl_oe_o}]
set_load -pin_load 0.0060 [get_ports {i2c_sda_oe_o}]
set_load -pin_load 0.0060 [get_ports {irq_soft_o}]
set_load -pin_load 0.0060 [get_ports {irq_timer_o}]
set_load -pin_load 0.0060 [get_ports {mbist_busy_o}]
set_load -pin_load 0.0060 [get_ports {mbist_done_o}]
set_load -pin_load 0.0060 [get_ports {mbist_failed_o}]
set_load -pin_load 0.0060 [get_ports {nmi_o}]
set_load -pin_load 0.0060 [get_ports {npu_aer_in_stb_o}]
set_load -pin_load 0.0060 [get_ports {npu_aer_out_vld_o}]
set_load -pin_load 0.0060 [get_ports {npu_irq_o}]
set_load -pin_load 0.0060 [get_ports {npu_ser_cs_n_o}]
set_load -pin_load 0.0060 [get_ports {npu_ser_miso_o}]
set_load -pin_load 0.0060 [get_ports {npu_ser_mosi_o}]
set_load -pin_load 0.0060 [get_ports {npu_ser_sck_o}]
set_load -pin_load 0.0060 [get_ports {qspi_irq_o}]
set_load -pin_load 0.0060 [get_ports {qspi_sck_o}]
set_load -pin_load 0.0060 [get_ports {spi_irq_o}]
set_load -pin_load 0.0060 [get_ports {spi_mosi_o}]
set_load -pin_load 0.0060 [get_ports {spi_sck_o}]
set_load -pin_load 0.0060 [get_ports {spw_do_o}]
set_load -pin_load 0.0060 [get_ports {spw_irq_o}]
set_load -pin_load 0.0060 [get_ports {spw_so_o}]
set_load -pin_load 0.0060 [get_ports {uart_irq_o}]
set_load -pin_load 0.0060 [get_ports {uart_tx_o}]
set_load -pin_load 0.0060 [get_ports {wdog_no}]
set_load -pin_load 0.0060 [get_ports {wdog_rst_o}]
set_load -pin_load 0.0060 [get_ports {alert_major_bus_o}]
set_load -pin_load 0.0060 [get_ports {alert_major_internal_o}]
set_load -pin_load 0.0060 [get_ports {alert_minor_o}]
set_load -pin_load 0.0060 [get_ports {eth_mbist_done_o[1]}]
set_load -pin_load 0.0060 [get_ports {eth_mbist_done_o[0]}]
set_load -pin_load 0.0060 [get_ports {eth_mbist_failed_o[1]}]
set_load -pin_load 0.0060 [get_ports {eth_mbist_failed_o[0]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[7]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[6]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[5]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[4]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[3]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[2]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[1]}]
set_load -pin_load 0.0060 [get_ports {eth_txd_o[0]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[15]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[14]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[13]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[12]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[11]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[10]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[9]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[8]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[7]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[6]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[5]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[4]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[3]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[2]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[1]}]
set_load -pin_load 0.0060 [get_ports {gpio_o[0]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[15]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[14]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[13]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[12]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[11]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[10]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[9]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[8]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[7]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[6]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[5]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[4]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[3]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[2]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[1]}]
set_load -pin_load 0.0060 [get_ports {gpio_oe_o[0]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[63]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[62]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[61]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[60]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[59]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[58]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[57]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[56]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[55]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[54]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[53]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[52]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[51]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[50]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[49]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[48]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[47]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[46]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[45]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[44]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[43]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[42]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[41]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[40]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[39]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[38]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[37]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[36]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[35]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[34]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[33]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[32]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[31]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[30]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[29]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[28]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[27]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[26]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[25]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[24]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[23]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[22]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[21]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[20]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[19]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[18]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[17]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[16]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[15]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[14]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[13]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[12]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[11]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[10]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[9]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[8]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[7]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[6]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[5]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[4]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[3]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[2]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[1]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_actual_o[0]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[12]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[11]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[10]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[9]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[8]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[7]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[6]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[5]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[4]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[3]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[2]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[1]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_addr_o[0]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[7]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[6]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[5]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[4]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[3]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[2]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[1]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_background_o[0]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[63]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[62]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[61]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[60]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[59]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[58]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[57]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[56]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[55]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[54]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[53]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[52]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[51]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[50]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[49]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[48]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[47]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[46]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[45]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[44]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[43]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[42]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[41]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[40]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[39]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[38]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[37]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[36]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[35]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[34]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[33]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[32]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[31]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[30]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[29]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[28]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[27]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[26]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[25]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[24]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[23]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[22]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[21]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[20]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[19]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[18]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[17]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[16]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[15]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[14]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[13]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[12]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[11]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[10]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[9]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[8]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[7]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[6]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[5]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[4]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[3]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[2]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[1]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_expected_o[0]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_phase_o[2]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_phase_o[1]}]
set_load -pin_load 0.0060 [get_ports {mbist_fail_phase_o[0]}]
set_load -pin_load 0.0060 [get_ports {qspi_cs_no[1]}]
set_load -pin_load 0.0060 [get_ports {qspi_cs_no[0]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_o[3]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_o[2]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_o[1]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_o[0]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_oe_o[3]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_oe_o[2]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_oe_o[1]}]
set_load -pin_load 0.0060 [get_ports {qspi_io_oe_o[0]}]
set_load -pin_load 0.0060 [get_ports {spi_cs_no[1]}]
set_load -pin_load 0.0060 [get_ports {spi_cs_no[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {can_rx_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_mdio_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rx_clk_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rx_dv_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rx_er_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_tx_clk_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i2c_scl_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i2c_sda_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {irq_external_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_ni}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {spi_miso_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {spw_di_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {spw_si_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uart_rx_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdog_dis_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {eth_rxd_i[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_i[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {qspi_io_i[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {qspi_io_i[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {qspi_io_i[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {qspi_io_i[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {strap_i[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {strap_i[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {strap_i[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {strap_i[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
