from pathlib import Path
import json,hashlib,runpy
R=Path.cwd();B=Path(__file__).resolve().parent
def pin(p):return dict(bytes=p.stat().st_size,sha256=hashlib.sha256(p.read_bytes()).hexdigest())
ns=runpy.run_path(str(R/'sw/tests/test_pcie_gen3_integrity_v20_retire.py'));ns['test_exact_generated_inverse_and_wrapper_bridge']()
names=['scripts/generate_pcie_integrity_retire_v20.py','scripts/check_pcie_gen3_continuous_rx_integrity_v20.py','hw/soc/rtl/pcie/soc_pcie_gen3_framer_rx_integrity_v20.v','hw/soc/rtl/pcie/soc_pcie_gen3_continuous_rx_integrity_v20.v','hw/soc/tb/cocotb/test_soc_pcie_gen3_continuous_rx_integrity_v20.py','hw/soc/tb/cocotb/Makefile.soc_pcie_gen3_continuous_rx_integrity_v20','sw/tests/test_pcie_gen3_integrity_v20_miter.py','sw/tests/test_pcie_gen3_continuous_rx_integrity_v20.py','sw/tests/test_pcie_gen3_integrity_v20_retire.py']
f=dict(status='FROZEN_V20_ELIGIBLE_ROOT_RETIRE_CONTROL_CANDIDATE',files={n:pin(R/n)for n in names},base='V19 exactsource inverse; publicmiterreferenceV17 preservesV19invalidstoragequarantine relation',scope='Only retirement read_keep==0 replacedby!read_any withknownrootexposure/countmask; allpayload/parser/writers/latency/constraints unchanged. Literal0/1/X/Z masks, actualfaults, full14public/miter andsame4nsnative stillpending; noacceptance.')
p=B/'source-freeze01.json';assert not p.exists();p.write_text(json.dumps(f,indent=2)+'\n');print(pin(p))
relation=dict(status='SOURCE_COMPOSITIONAL_FOUR_STATE_ARGUMENT_ACTUAL_TESTS_PENDING',freeze=pin(p),steps=['Eachleafproceduraldefaults forceeligible known0/1. Onlytrue addressmatch&&keep!=0&&verdict selectsleaf; unknowncondition takesdefault.', 'eligible1 therefore impliesatleastoneknown1 inkeep; unknown-onlykeep cannotpass !=0 test. Literalotherkeep/payloadbits mayremainX/Z.', 'Foroneknownaddress, atmostonesloteligible. Balancedpayloadmux selectssoleeligiblepayload; noneeligible produceszero. KnownflagsensureliteralZ unchanged.', 'Eachlane finalprocedural r<read_count gate eitherpasses payload+eligible together orleavesbothzero. Unknowncountcomparison masksboth.', 'Keptlane payloadkeep hasatleastoneknown1 iff eligible. Thus concatenatedread_keep==0 isalwaysknown andtrue iff allmaskedeligibleflagsare0; !read_anyisidentical.', 'Only retirementcontrol usesnewpredicate; allotherports andwriters exactV19. Sourceinverse doesnot prove allreachableprotocolinputs byitself; actualcomponent/miter/faultcontrols required.'],test_plan=dict(random_literal_cases=12288,rings=[16,64,128],fourstate_local_keep_verdict=4096,fourstate_all_count_words=4096,fourstate_all_pointer_words=1024,selected_payload_and_mask_cases=59,isolated_sensitivity_cases=31,actual_read_control_mutants=9,payload_Z_conversion_mutant=1,whole_DUT_miter_mutants=7,parser_CRC_mutants=8,public_cases=14,miter_reference='V17',excluded_MAX4118=2),limits='Finite actualcasecoverage andcompositional sourceargument, not exhaustivewholeDUTformal or timingclosure. Alloriginal4ns and2GiBlimits held.')
(B/'fourstate-relation01.json').write_text(json.dumps(relation,indent=2)+'\n')
