#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

"""Which netlist flip-flop is which RTL bit, derived from a trace of
both designs on the clean run -- docs/74.

    gl_map.py --emit-rtl-trace <fi_rtl_trace.v>
    gl_map.py --rtl-trace <rtl.trace> --gl-trace <gl.trace> \\
              --flops <flops.tsv> --out <map.json> [--report <map.txt>]
    gl_map.py --emit-rf <map.json> <flops.tsv> <fi_gl_rf.vh>

WHY A TRACE AND NOT A NAME

docs/32 section 4.2 found that a flip-flop's name in the netlist is
whichever alias yosys kept: a rail carried its consumer's name, and a
bit that had been `_0255_` in one harden was `_0253_` in the next. On
this netlist the IF/ID instruction register's bits 19:15 are named after
the register file's read-address port, the fetch address is named after
`crash_dump_o`, and three controller registers have no name at all
(hw/soc/out/gl74/census_by_name.txt). A name is a hypothesis about
which flip-flop this is. The trace is the measurement.

THE MEASUREMENT

Both benches run the clean workload with nothing injected and write,
on every falling clock edge, the value of every register: the RTL bench
its 2,451 site bits (through the second root this module generates,
hw/soc/flow/fi_core.sh's FI_EXTRA_ROOT), the gate-level bench its
5,873 flip-flops (tb_soc_fi_gl.v's +trace). Two bits that are the same
storage have the same trace, cycle for cycle, for 18,682 cycles; a
netlist flip-flop that stores the complement has the complemented
trace. So an RTL bit maps to the netlist flip-flops whose trace equals
its own or its complement, and the census then says, for every RTL
bit, whether it has exactly one twin, several (a duplicate), or none
(deleted or re-encoded), and for every netlist flip-flop under
`u_ibex.` whether it is some RTL bit's twin or something synthesis
made.

WHAT A TRACE CANNOT DECIDE

Two registers that hold the same value throughout the clean run have
the same trace and cannot be told apart by it: a bit that is constant
over the run, or two bits that happen to agree on every cycle of this
workload. The mapping therefore prefers, among trace-equal candidates,
the one whose netlist name matches the RTL path, and marks every
mapping with how it was decided -- `trace+name`, `trace` (unique by
trace, name differs), `ambiguous` (several by trace, none by name;
NOT injected), `constant` (the RTL bit never changes in the clean run,
so the trace says nothing; mapped by name only if a same-named flop
exists, else not injected), and `none`. The campaign injects only
through `trace+name` and `trace`, and docs/74 reports the others.
"""

import argparse
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import targets                                        # noqa: E402
from gl_netlist import plain, verilog_ref             # noqa: E402


# ---------------------------------------------------------------------
# the RTL trace root
# ---------------------------------------------------------------------
def site_layout():
    """(site index, site, offset) with the flat bit of site k bit b at
    offset_k + b."""
    out = []
    off = 0
    for k, s in enumerate(targets.SITES):
        out.append((k, s, off))
        off += s.width
    return out, off


def emit_rtl_trace(path):
    layout, width = site_layout()
    lines = []
    lines.append("// GENERATED by hw/soc/fi/gl_map.py -- do not edit.")
    lines.append("// A second elaboration root that traces every campaign site of")
    lines.append("// tb_soc_fi.v's design per cycle. %d bits, %d sites."
                 % (width, len(layout)))
    lines.append("`timescale 1ns / 1ps")
    lines.append("module fi_rtl_trace;")
    lines.append("  wire [%d:0] v = {" % (width - 1))
    for k, s, off in reversed(layout):
        lines.append("    tb_soc_fi.dut.u_ibex.%s%s" % (s.path, "," if k else ""))
    lines.append("  };")
    lines.append("  reg [1023:0] f;")
    lines.append("  integer fd = 0;")
    lines.append("  initial if ($value$plusargs(\"trace=%s\", f)) fd = $fopen(f, \"w\");")
    lines.append("  always @(negedge tb_soc_fi.clk)")
    lines.append("    if (tb_soc_fi.rst_n && fd) $fwrite(fd, \"%b\\n\", v);")
    lines.append("endmodule")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------
# reading traces
# ---------------------------------------------------------------------
def read_trace(path):
    """Rows of '0'/'1'/'x' text, MSB first as Verilog prints them; returns
    a list of per-bit column strings indexed by bit number (bit 0 is
    the LAST character of a row)."""
    rows = [line.rstrip("\n") for line in open(path) if line.strip()]
    width = len(rows[0])
    for r in rows:
        if len(r) != width:
            sys.exit("ragged trace %s" % path)
    # transpose: column j (from the right) is bit j
    cols = ["".join(r[width - 1 - j] for r in rows) for j in range(width)]
    return cols, len(rows)


def complement(col):
    return col.translate(str.maketrans("01", "10"))


# ---------------------------------------------------------------------
# the aliases, from hw/soc/flow/fi_gl_alias.sh's JSON
# ---------------------------------------------------------------------
_GENBLK = __import__("re").compile(r"(^|\.)genblk\d+\.")


def _norm(name):
    """Yosys puts an anonymous generate scope (`genblk3`) in the
    multiplier's path where Icarus does not; hw/soc/fi/coverage.py
    normalises it the same way."""
    return _GENBLK.sub(r"\1", name)


def load_aliases(path):
    """RTL site path (Icarus form, relative to ibex_top) and bit ->
    the set of (name, bit) every public wire on that net carries in the
    elaborated, flattened, un-renamed design, each prefixed `u_ibex.`
    so it can be looked up among the netlist's Q nets."""
    j = json.load(open(path))
    mod = j["modules"]["ibex_top"]
    nn = mod["netnames"]
    by_bit = collections.defaultdict(set)
    named = {}
    for name, d in nn.items():
        if d.get("hide_name"):
            continue
        for i, b in enumerate(d["bits"]):
            if isinstance(b, str):
                continue           # a constant
            by_bit[b].add((name, i))
            named[(_norm(name), i)] = b
    # The RTL census: every bit a flip-flop cell drives after opt_clean.
    # A site bit that is not in this set is one synthesis removed before
    # it ever reached a technology cell -- docs/42 section 4.2's three
    # IF-stage registers and its one mcountinhibit bit, and whatever
    # else the parameters make constant.  fi_coverage.sh counts the same
    # set; this reads it from the same elaboration's JSON.
    ff = set()
    for cell in mod["cells"].values():
        if cell["type"] in ("$dff", "$adff", "$dffe", "$adffe", "$sdff",
                            "$sdffe", "$sdffce", "$dffsr", "$dffsre",
                            "$adlatch", "$dlatch"):
            for b in cell["connections"].get("Q", []):
                if not isinstance(b, str):
                    ff.add(b)
    return by_bit, named, ff


def rtl_census_has(aliases, path, bit):
    """Whether the RTL bit is stored by a flip-flop after the RTL
    census's own opt_clean; None when no alias JSON was given."""
    if aliases is None:
        return None
    by_bit, named, ff = aliases
    b = named.get((path, bit))
    return b is not None and b in ff


def alias_candidates(aliases, path, bit, by_name):
    """Netlist flop indices whose Q-net name is an alias of the RTL
    bit, and the alias names themselves."""
    if aliases is None:
        return [], set()
    by_bit, named, ff = aliases
    b = named.get((path, bit))
    if b is None:
        return [], set()
    names = set()
    idxs = set()
    for name, i in by_bit[b]:
        names.add(("u_ibex." + name, i))
        for key in (("u_ibex." + name, i), ("u_ibex." + name, None)):
            if key in by_name:
                idxs.add(by_name[key])
    return sorted(idxs), names


# ---------------------------------------------------------------------
# the mapping
# ---------------------------------------------------------------------
def derive(rtl_cols, gl_cols, flops, aliases=None):
    layout, width = site_layout()
    if len(rtl_cols) != width:
        sys.exit("RTL trace is %d bits wide, targets.py says %d"
                 % (len(rtl_cols), width))
    if len(gl_cols) != len(flops):
        sys.exit("gate-level trace is %d bits wide, flops.tsv lists %d"
                 % (len(gl_cols), len(flops)))

    by_trace = collections.defaultdict(list)
    for f in flops:
        by_trace[gl_cols[f["idx"]]].append(f["idx"])
    by_name = {plain(f["q"]): f["idx"] for f in flops}

    entries = []
    used = collections.Counter()
    for k, s, off in layout:
        for b in range(s.width):
            col = rtl_cols[off + b]
            name_key = ("u_ibex." + s.path, b if s.width > 1 else None)
            name_idx = by_name.get(name_key)
            if name_idx is None:
                name_idx = by_name.get(("u_ibex." + s.path, b))
            const = col.count(col[0]) == len(col)
            same = by_trace.get(col, [])
            inv = by_trace.get(complement(col), [])
            cands = [(i, 0) for i in same] + [(i, 1) for i in inv]
            al_idx, al_names = alias_candidates(aliases, s.path, b, by_name)
            if name_idx is not None and name_idx not in al_idx:
                al_idx = [name_idx] + al_idx
            e = {"site": k, "stratum": s.stratum, "name": s.name,
                 "path": s.path, "bit": b, "rtl_flat": off + b,
                 "constant": const, "candidates": cands,
                 "aliases": al_idx,
                 "name_idx": name_idx, "gl": None, "pol": 0, "how": "none"}
            # The decision, in order of how much it rests on:
            #   trace+name   one flop by trace, and it carries the RTL's
            #                own name or one of its aliases
            #   trace        one flop by trace, no name agrees
            #   trace&alias  several by trace, exactly one is an alias
            #   alias        the trace says nothing (constant over the
            #                run) and exactly one flop carries an alias
            #   ambiguous    several by trace, none or several by alias
            #   constant     constant over the run and no alias survives
            #   none         a live bit with no trace twin at all
            trace_named = [(i, p) for i, p in cands if i in al_idx]
            if const:
                # A name-only mapping is still checked against the trace
                # it has: the RTL bit is constant, so the flop under the
                # alias must be constant at the same value (or, stored
                # inverted, at the other).  A flop that toggles under an
                # RTL register's name is a re-encoded register that kept
                # the name -- yosys's fsm pass on ctrl_fsm_cs did exactly
                # that -- and it is not the RTL bit.  Control 5 of
                # gl_campaign.py is what found this.
                if len(al_idx) == 1:
                    gcol = gl_cols[al_idx[0]]
                    if gcol == col:
                        e.update(gl=al_idx[0], pol=0, how="alias")
                    elif gcol == complement(col):
                        e.update(gl=al_idx[0], pol=1, how="alias")
                    else:
                        e["how"] = "alias(withdrawn)"
                        e["withdrawn_idx"] = al_idx[0]
                elif len(al_idx) > 1:
                    e["how"] = "ambiguous"
                else:
                    e["how"] = "constant"
            elif not cands:
                e["how"] = "none"
            elif len(cands) == 1:
                i, p = cands[0]
                e.update(gl=i, pol=p,
                         how="trace+name" if i in al_idx else "trace")
            elif len(trace_named) == 1:
                i, p = trace_named[0]
                e.update(gl=i, pol=p, how="trace&alias")
            else:
                e["how"] = "ambiguous"
            # A trace-only identification of a bit that barely moves is
            # a coincidence waiting to happen: 5,873 flops, and a bit
            # that toggles twice has few distinct traces to be equal to.
            # Sixteen transitions or an agreeing alias, or it is not
            # injected.
            if e["how"] == "trace":
                e["transitions"] = sum(1 for t in range(1, len(col))
                                       if col[t] != col[t - 1])
                if e["transitions"] < 16:
                    e.update(gl=None, how="trace(weak)")
            # Removed by synthesis before mapping: the RTL census has no
            # flip-flop for it.  Whatever the trace matched is another
            # register's flop, and the RTL record measured nothing
            # physical (docs/42 section 4.4 item 1).
            e["in_rtl_census"] = rtl_census_has(aliases, s.path, b)
            if e["in_rtl_census"] is False and e["gl"] is not None:
                e.update(deleted_twin=e["gl"], gl=None, how="deleted")
            elif e["in_rtl_census"] is False:
                e["how"] = "deleted"
            if e["gl"] is not None:
                used[e["gl"]] += 1
            entries.append(e)
    # Merged: two live RTL registers that synthesis stored in ONE flop
    # (opt_merge: same D, same reset, same enable -- Ibex's duplicated
    # instruction register, ibex_top's multi-bit busy encoding).  An
    # upset in that flop is an upset in both RTL registers at once, so
    # the record is replayed but is not like-for-like, and the report
    # keeps it apart.
    for e in entries:
        if e["gl"] is not None and used[e["gl"]] > 1:
            e["merged_with"] = [x["stratum"] + "." + x["name"] + "[%d]" % x["bit"]
                                for x in entries
                                if x["gl"] == e["gl"] and x is not e]
            e["how"] = "merged"
    return entries, used, by_trace


def align(rtl_cols, gl_cols, flops):
    """The two benches release reset at the same clock edge, but the RTL
    flops evaluate that edge before the bench's reset assignment and the
    netlist's flops -- behind a clock tree of buffer cells -- after it,
    so the netlist leaves reset one clock earlier than the RTL and its
    trace is one row ahead.  This does not assume that: it measures the
    shift on every register-file data bit that toggles, over -2..+2 rows,
    and refuses to map unless exactly one shift makes every one of them
    identical.  The same shift is what the campaign applies to a
    replayed cycle."""
    by_name = {plain(f["q"]): f["idx"] for f in flops}
    layout, _ = site_layout()
    probes = []
    for k, s, off in layout:
        if s.stratum != "regfile":
            continue
        for b in range(s.width):
            gi = by_name.get(("u_ibex." + s.path, b))
            if gi is None:
                continue
            col = rtl_cols[off + b]
            if col.count(col[0]) != len(col):
                probes.append((off + b, gi))
    if len(probes) < 100:
        sys.exit("only %d register-file bits toggle in the clean run and "
                 "carry their name; not enough to align" % len(probes))
    good = []
    for sh in (-2, -1, 0, 1, 2):
        ok = 0
        for r, g in probes:
            a = rtl_cols[r]
            bcol = gl_cols[g]
            if sh >= 0:
                a2, b2 = a[:len(a) - sh] if sh else a, bcol[sh:]
            else:
                a2, b2 = a[-sh:], bcol[:len(bcol) + sh]
            n = min(len(a2), len(b2))
            if a2[:n] == b2[:n]:
                ok += 1
        if ok == len(probes):
            good.append(sh)
    if len(good) != 1:
        sys.exit("the traces align at %s (of -2..2) on %d probe bits; "
                 "exactly one shift is required" % (good, len(probes)))
    sh = good[0]
    # gate-level row t corresponds to RTL row t - sh
    if sh >= 0:
        rtl2 = [c[:len(c) - sh] if sh else c for c in rtl_cols]
        gl2 = [c[sh:] for c in gl_cols]
    else:
        rtl2 = [c[-sh:] for c in rtl_cols]
        gl2 = [c[:len(c) + sh] for c in gl_cols]
    n = min(len(rtl2[0]), len(gl2[0]))
    rtl2 = [c[:n] for c in rtl2]
    gl2 = [c[:n] for c in gl2]
    return sh, rtl2, gl2, n


def report(entries, used, flops, gl_cols, rtl_cols, say):
    how = collections.Counter(e["how"] for e in entries)
    say("RTL site bits: %d" % len(entries))
    for h in ("trace+name", "trace", "trace&alias", "alias", "merged",
              "ambiguous", "constant", "trace(weak)", "alias(withdrawn)",
              "deleted", "none"):
        say("  %-18s %d" % (h, how.get(h, 0)))
    inv = sum(1 for e in entries if e["gl"] is not None and e["pol"])
    say("  mapped with inverted storage polarity: %d" % inv)
    multi = [(i, n) for i, n in used.items() if n > 1]
    say("  netlist flops that are the twin of more than one RTL bit: %d"
        % len(multi))
    say("")
    say("per stratum: bits / mapped / of which by trace alone / unmapped")
    per = collections.defaultdict(lambda: [0, 0, 0, 0])
    for e in entries:
        d = per[e["stratum"]]
        d[0] += 1
        if e["gl"] is not None:
            d[1] += 1
            if e["how"] in ("trace", "trace&alias"):
                d[2] += 1
        else:
            d[3] += 1
    for st in targets.STRATA:
        d = per[st]
        say("  %-12s %5d %5d %5d %5d" % (st, d[0], d[1], d[2], d[3]))
    say("")
    say("unmapped RTL bits, by site:")
    grp = collections.defaultdict(list)
    for e in entries:
        if e["gl"] is None:
            grp[(e["stratum"], e["name"], e["how"])].append(e["bit"])
    for (st, name, h), bits in sorted(grp.items()):
        say("  %-12s %-26s %-10s %d bit(s): %s"
            % (st, name, h, len(bits), _ranges(bits)))
    say("")
    say("RTL bits that share a netlist flop with another live RTL bit (merged):")
    seen = set()
    for e in entries:
        if e["how"] == "merged" and e["gl"] not in seen:
            seen.add(e["gl"])
            say("  #%-5d %-70s <- %s.%s[%d], %s" % (
                e["gl"], flops[e["gl"]]["q"], e["stratum"], e["name"], e["bit"],
                ", ".join(e["merged_with"])))
    say("")
    say("RTL bits removed by synthesis (no flip-flop in the RTL census):")
    grp = collections.defaultdict(list)
    for e in entries:
        if e["how"] == "deleted":
            grp[(e["stratum"], e["name"])].append(e["bit"])
    for (st, name), bits in sorted(grp.items()):
        say("  %-12s %-26s %d bit(s): %s" % (st, name, len(bits), _ranges(bits)))
    say("")
    say("RTL bits whose alias-named flop toggles while the RTL bit is constant (withdrawn):")
    for e in entries:
        if e["how"] == "alias(withdrawn)":
            say("  %-12s %-26s[%2d] alias flop #%-5d %s" % (
                e["stratum"], e["name"], e["bit"], e["withdrawn_idx"],
                flops[e["withdrawn_idx"]]["q"]))
    say("")
    say("RTL bits mapped by trace to a flop of ANOTHER name (no alias agrees):")
    for e in entries:
        if e["how"] == "trace":
            say("  %-12s %-26s[%2d] -> #%-5d %s%s"
                % (e["stratum"], e["name"], e["bit"], e["gl"],
                   flops[e["gl"]]["q"], "  (inverted)" if e["pol"] else ""))
    say("")
    # the other direction
    core = [f for f in flops if plain(f["q"])[0].startswith("u_ibex.")]
    twins = set(e["gl"] for e in entries if e["gl"] is not None)
    rtl_by_trace = collections.defaultdict(list)
    for e in entries:
        rtl_by_trace[rtl_cols[e["rtl_flat"]]].append(e)
    say("netlist flip-flops under u_ibex.: %d; twins of an RTL bit: %d; "
        "not: %d" % (len(core), sum(1 for f in core if f["idx"] in twins),
                     sum(1 for f in core if f["idx"] not in twins)))
    say("  of those not: constant over the clean run / trace-equal to some "
        "RTL bit (a duplicate) / trace-equal to nothing in the RTL site table")
    cconst = cdup = cnew = 0
    newnames = collections.Counter()
    dupnames = collections.Counter()
    for f in core:
        if f["idx"] in twins:
            continue
        col = gl_cols[f["idx"]]
        if col.count(col[0]) == len(col):
            cconst += 1
        elif col in rtl_by_trace or complement(col) in rtl_by_trace:
            cdup += 1
            dupnames[plain(f["q"])[0]] += 1
        else:
            cnew += 1
            newnames[plain(f["q"])[0]] += 1
    say("  %d / %d / %d" % (cconst, cdup, cnew))
    say("  duplicates, by name:")
    for n, c in sorted(dupnames.items()):
        say("    %-72s %d" % (n, c))
    say("  trace-equal to nothing in the site table, by name:")
    for n, c in sorted(newnames.items()):
        say("    %-72s %d" % (n, c))


def _ranges(bits):
    bits = sorted(bits)
    out = []
    start = prev = bits[0]
    for b in bits[1:]:
        if b == prev + 1:
            prev = b
            continue
        out.append("%d" % start if start == prev else "%d-%d" % (start, prev))
        start = prev = b
    out.append("%d" % start if start == prev else "%d-%d" % (start, prev))
    return ",".join(out)


def read_flops(path):
    out = []
    with open(path) as fh:
        hdr = fh.readline().rstrip("\n").split("\t")
        for line in fh:
            row = dict(zip(hdr, line.rstrip("\n").split("\t")))
            row["idx"] = int(row["idx"])
            out.append(row)
    return out


# ---------------------------------------------------------------------
# the register-file shadow wiring
# ---------------------------------------------------------------------
def emit_rf(map_path, flops_path, out_path):
    m = json.load(open(map_path))
    flops = read_flops(flops_path)
    ent = {(e["stratum"], e["name"], e["bit"]): e for e in m["entries"]}

    def ref(key):
        e = ent.get(key)
        if e is None or e["gl"] is None:
            sys.exit("the register-file shadow needs %s and the mapping "
                     "has no flop for it" % (key,))
        r = verilog_ref(flops[e["gl"]]["q"])
        return ("~" + r) if e["pol"] else r

    lines = ["// GENERATED by hw/soc/fi/gl_map.py from %s -- do not edit."
             % os.path.basename(map_path),
             "// The register file's storage, the scrub pointer and the read",
             "// addresses, read out of the netlist by the mapped names, with",
             "// the storage polarity the trace found.",
             "  wire [991:0] fi_rf_data;",
             "  wire [216:0] fi_rf_chk;",
             "  wire [4:0]   fi_rf_ptr, fi_rf_ra, fi_rf_rb;"]
    for i in range(1, 32):
        for b in range(32):
            lines.append("  assign fi_rf_data[%d] = %s;"
                         % (32 * (i - 1) + b, ref(("regfile", "x%d" % i, b))))
        for b in range(7):
            lines.append("  assign fi_rf_chk[%d] = %s;"
                         % (7 * (i - 1) + b, ref(("regfile_ecc", "x%d_chk" % i, b))))
    for b in range(5):
        lines.append("  assign fi_rf_ptr[%d] = %s;"
                     % (b, ref(("regfile_ecc", "scrub_ptr", b))))
    # raddr_a = instr_rdata_id[19:15], raddr_b = instr_rdata_id[24:20]
    # (ibex_decoder: rf_raddr_a_o = instr[19:15], rf_raddr_b_o = instr[24:20])
    for b in range(5):
        lines.append("  assign fi_rf_ra[%d] = %s;"
                     % (b, ref(("if_id", "instr_rdata_id_o", 15 + b))))
        lines.append("  assign fi_rf_rb[%d] = %s;"
                     % (b, ref(("if_id", "instr_rdata_id_o", 20 + b))))
    lines.append("  fi_rf_shadow u_rf_shadow (")
    lines.append("      .clk_i (clk), .rst_ni (rst_n),")
    lines.append("      .data_i (fi_rf_data), .chk_i (fi_rf_chk), .ptr_i (fi_rf_ptr),")
    lines.append("      .raddr_a_i (fi_rf_ra), .raddr_b_i (fi_rf_rb),")
    lines.append("      .sec_cycles_o (rf_sec_cycles), .ded_cycles_o (rf_ded_cycles),")
    lines.append("      .sec_seen_o (rf_sec_seen), .ded_seen_o (rf_ded_seen));")
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-rtl-trace", default=None)
    ap.add_argument("--rtl-trace", default=None)
    ap.add_argument("--gl-trace", default=None)
    ap.add_argument("--flops", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--report", default=None)
    ap.add_argument("--alias", default=None,
                    help="fi_alias.json from hw/soc/flow/fi_gl_alias.sh")
    ap.add_argument("--emit-rf", nargs=3, default=None,
                    metavar=("MAP", "FLOPS", "VH"))
    args = ap.parse_args()
    if args.emit_rtl_trace:
        emit_rtl_trace(args.emit_rtl_trace)
        return
    if args.emit_rf:
        emit_rf(*args.emit_rf)
        return
    flops = read_flops(args.flops)
    rtl_cols, n_rtl = read_trace(args.rtl_trace)
    gl_cols, n_gl = read_trace(args.gl_trace)
    shift, rtl_cols, gl_cols, n = align(rtl_cols, gl_cols, flops)
    aliases = load_aliases(args.alias) if args.alias else None
    entries, used, _ = derive(rtl_cols, gl_cols, flops, aliases)
    out = {"cycles": n, "rtl_rows": n_rtl, "gl_rows": n_gl,
           "gl_row_shift": shift,
           "cycle_rule": "gl_cycle = rtl_cycle + (%d)" % shift,
           "rtl_bits": len(entries), "gl_flops": len(flops),
           "entries": entries}
    with open(args.out, "w") as fh:
        json.dump(out, fh, indent=1)
    lines = []

    def say(s):
        print(s)
        lines.append(s)
    say("clean run: RTL %d rows, gate level %d rows; aligned on %d rows "
        "with the gate-level row shifted by %d (gate-level row t is RTL "
        "row t - (%d)); a record's cycle is replayed as gl_cycle = "
        "rtl_cycle + (%d)" % (n_rtl, n_gl, n, shift, shift, shift))
    report(entries, used, flops, gl_cols, rtl_cols, say)
    if args.report:
        with open(args.report, "w") as fh:
            fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
