#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

"""Generate the counterfactual copy of soc_npu.v: the connection with its
one recovery mechanism removed.

    npu_counterfactual.py <out.v>

WHY THIS EXISTS

"The protection works" is not a measurement unless the same experiment on
the design WITHOUT it produces a different number.  `docs/41` section 8.3
built its whole result that way -- the same draws, target by target,
against a `HARDEN = 0` build -- and `docs/43` section 5.4 replayed a
named record set against isolation builds for the same reason.

`hw/soc/rtl/soc_npu.v` has exactly ONE recovery mechanism of its own.
Everything else it carries it inherited: the two queues are
`hw/rtl/aer_fifo.v` and their pointer voting, entry parity and dual-rail
`rd_valid` come with them, and `aer_fifo.v` is in the FROZEN directory
`docs/34` pins, so there is no `HARDEN = 0` to build and none may be
made.  What the connection added is the BOUNDED WAIT on an
injection-queue fetch:

    E_FETCH: begin
      if (inj_rd_valid) ...
      else if (ev_wait == FETCHMAX_4) ev_state <= E_IDLE;   <- this
      else ev_wait <= ev_wait + 1;
    end

and its report, `fetch_expire`, which latches `IRQ_CAUSE.FETCH_ER`.  It
exists because `aer_fifo` may legitimately answer a read with nothing --
an entry whose stored parity fails is discarded and `rd_valid` is held
low -- so a fetch that never returns would hang the engine.
`hw/rtl/pilot_top.v` section 8 has the same bound on its own dispatcher
for the same reason, and `docs/16` section 5.1 is the campaign that made
it necessary: five HANG outcomes, one deadlock, no fault indication at
all.

`FETCH_MAX` is constrained to 1..15 by an elaboration guard, so the
mechanism cannot be turned off with a parameter.  The counterfactual is
therefore a scratch copy, built by an ASSERTED substitution: if the text
below is not found exactly, this script fails.  A generator that quietly
produced an unmodified copy would give a counterfactual identical to the
design, which reads as "the mechanism does nothing" -- and `docs/49`
section 8.1 is four pages on a flow step that elaborates, exits zero and
changes nothing.

THE COPY IS NOT IN THE SOURCE TREE.  `hw/soc/flow/fi_npu.sh` takes it
through `SOC_NPU_SRC` and writes a `SUBSTITUTED` marker into the build
directory, so a records.csv from this build cannot be mistaken for one
from the design of record.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(os.path.dirname(HERE), "rtl", "soc_npu.v")

# The two substitutions, each stated as the exact text it replaces.  They
# are whole statements rather than fragments so that a reader can check
# by eye that nothing else changed.
EDITS = [
    (
        """        E_FETCH: begin
          if (inj_rd_valid) begin
            ev_word  <= inj_rd_data;
            ev_state <= E_DECIDE;
          end else if (ev_wait == FETCHMAX_4) begin
            ev_state <= E_IDLE;
          end else begin
            ev_wait <= ev_wait + 4'd1;
          end
        end""",
        """        // COUNTERFACTUAL (hw/soc/fi/npu_counterfactual.py, docs/52
        // section 6.5): the bounded wait is REMOVED. The engine waits in
        // E_FETCH until rd_valid arrives, which aer_fifo is entitled
        // never to send for an entry whose stored parity failed.
        E_FETCH: begin
          if (inj_rd_valid) begin
            ev_word  <= inj_rd_data;
            ev_state <= E_DECIDE;
          end
        end""",
    ),
    (
        """  wire fetch_expire = (ev_state == E_FETCH) && !inj_rd_valid
                   && (ev_wait == FETCHMAX_4);""",
        """  // COUNTERFACTUAL: nothing expires, so nothing is reported and
  // IRQ_CAUSE.FETCH_ER can never be raised.
  wire fetch_expire = 1'b0;""",
    ),
]


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: npu_counterfactual.py <out.v>")
    text = open(SRC).read()
    for old, new in EDITS:
        if text.count(old) != 1:
            sys.exit("the counterfactual's anchor text is not present "
                     "exactly once in %s. soc_npu.v has changed and this "
                     "script must be re-read against it rather than "
                     "loosened:\n---\n%s\n---" % (SRC, old))
        text = text.replace(old, new)
    # The generated file must announce itself in its first line, because
    # the one way this goes wrong is a scratch copy being read as the
    # design.
    banner = ("// GENERATED by hw/soc/fi/npu_counterfactual.py from "
              "hw/soc/rtl/soc_npu.v.\n"
              "// THIS IS NOT THE DESIGN. The engine's bounded fetch wait "
              "and its report\n"
              "// are removed, so that docs/52 section 6.5 can measure "
              "what they buy.\n"
              "// Do not add this file to the tree.\n")
    open(sys.argv[1], "w").write(banner + text)
    print("wrote %s (%d substitutions asserted)" % (sys.argv[1], len(EDITS)))


if __name__ == "__main__":
    main()
