from pathlib import Path
import hashlib,json,ast
B=Path(__file__).resolve().parent;R=B.parents[3];OLD=B.parent/'pcie-divider-v7-wire-v5-20261005';G=Path('/dev/shm/nssoc-div4-v7-power-v2-layout-01');C=Path('/dev/shm/nssoc-div4-v7-power-v2-checks-02');P=B.parent/'pcie-divider-v7-power-v1-20261005'
def pin(p):
 with Path(p).open('rb') as f:return {'bytes':Path(p).stat().st_size,'sha256':hashlib.file_digest(f,'sha256').hexdigest()}
closed=json.loads((C/'result.json').read_text());assert closed['status']=='PASS_DIV4_V7_POWER_V2_STANDALONE_MAIN_DRC_STRICT_DEEP_FLAT_LVS_LEF_NEGATIVE_CONTROLS_ONLY';assert len(closed['steps'])==21;assert closed['outputs']=={n:pin(C/n)['sha256'] for n in closed['outputs']}
assert closed['power_geometry_audit']['independent_raw_gds_boundary_instances_verified']==47
np=P/'native03-saved-peer-rx.json';nativepeer=json.loads(np.read_text());assert nativepeer['status']=='PASS_POWER_V2_SAVED_NATIVE21_AND_GEOMETRY4' and nativepeer['findings']==[];assert nativepeer['checks']==pin(C/'result.json') and nativepeer['geometry']==pin(C/'power-geometry.json') and nativepeer['GDS']==pin(G/'nssoc_clock_div4_v7_power_v2_layout.gds');prior=json.loads((OLD/'geometry-source-freeze.json').read_text());inputs=dict(prior['inputs']);assert inputs=={p:pin(p) for p in inputs}
paths=[*G.rglob('*'),*C.rglob('*'),*B.glob('*.py'),B/'native_unsimplified.lvs',B/'draft-source-bridge.json',B/'draft-only.json',OLD/'geometry-source-freeze.json',OLD/'geometry-source-only-peer.json',OLD/'saved-geometry-peer.json',P/'source-freeze03.json',P/'source-only-peer03-rx.json',np,P/'native03-finite-review-ready.json']
for p in paths:
 if p.is_file():inputs[str(p)]=pin(p)
record={'status':'FROZEN_FRESH_POWER_V2_UNSIMPLIFIED_NATIVE_GEOMETRY_BEFORE_EXTRACTION','inputs':inputs,'producer_sources':{str(B/n):pin(B/n) for n in ['run_geometry.py','probe_native_cells.py','probe_device_locations.py','probe_wire_components.py','probe_terminal_anchors.py','prepare_anchors.py','bind_source_ids.py','native_unsimplified.lvs']},'source_expected_census':{'devices':91,'terminals':283,'metal_terminals':198,'body_terminals':85,'anchors':205,'ports':7,'conductors':37},'actual_prior_hierarchy_census':{'devices':91,'via_stack':634,'all_leaves':725},'complete_native_cluster_partition_expected':{'raw':72,'electrical':38,'body_only':1,'auxiliary':34},'prior_completed_native_layout':pin(C/'result.json'),'new_native_extraction':True,'original_source_and_all_intrinsic_models_unchanged':True,'no_qualified_pex':True,'scope':'Actual power-overlay GDS passed mainDRC, strictdeep/flatLVS and intentional native controls. Fresh unsimplified native extraction must independently rediscover all91devices/283terminals/205anchors and exact fullsource bijection, all72 rawclusters retained. Actual47newvias change leafcensus only; no transistor, body, electricalcluster or anchor threshold relaxed. No RC or loaded waveform claim.'}
p=B/'geometry-source-freeze.json';assert not p.exists();p.write_text(json.dumps(record,indent=2)+'\n');print(pin(p),len(inputs))
