#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
"""Copy the small, checkable evidence out of the run trees and into git.

    collect_evidence.py [--check]

WHY THIS EXISTS. `.gitignore` excludes every `runs/` tree, for a good
reason: a 113 MB GDS does not belong in a repository. The consequence
was that NOTHING the corpus says about layout could be checked from a
clone -- not the zero routing errors, not the unique LVS match, not the
setup slack, not one power figure. A quarter of the test suite skipped,
each skip naming honestly what it could not reach, and an external
review called it the single biggest gap here. A skip is not a pass.

The evidence, though, is small. `final/metrics.json` is about 10 kB and
`resolved.json` about 30 kB: between them they carry the instance
counts, the utilisation, every corner's slack, the DRC and antenna
counts, and the full resolved configuration the run was given. Fifteen
runs is under a megabyte. That is what this copies.

WHAT IS EVIDENCE AND WHAT IS NOT. A committed `metrics.json` is a
record of what a run reported, hash-pinned in `docs/80`. It is NOT the
run: it cannot be re-derived from this repository, and a reader who
wants to re-derive it needs the PDK, the flow and four hours. The
tests that read it say "checked against the recorded artefact" and not
"checked", and the distinction is the point.

WHAT IT DELIBERATELY DOES NOT COPY. Netlists, DEF, GDS, SPICE, reports
and logs. They are large, and every claim that needs them stays a skip
whose message names the digest the absent file would have to match.
"""

import argparse
import hashlib
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "evidence"

# run tag -> the directory that holds it. Every one of these is cited by
# a document; a run that no document cites does not belong here.
RUNS = {
    "full3": "hw/soc/pnr/runs",
    "npu2": "hw/soc/pnr/runs",
    "s71boot": "hw/soc/pnr/runs",
    "s77gate": "hw/soc/pnr/runs",
    "s81ptd": "hw/soc/pnr/runs",
    "s83romecc5": "hw/soc/pnr/runs",
    "s83ant": "hw/soc/pnr/runs",
    "s83lvsbb2": "hw/soc/pnr/runs",
    "signoff-6x2": "hw/openlane/pilot_ihp/runs",
    "signoff-6x2-gated": "hw/openlane/pilot_ihp/runs",
    "submission-6x2": "hw/openlane/pilot_ihp/runs",
    "submission-6x2-gated": "hw/openlane/pilot_ihp/runs",
    "g0gates2": "hw/openlane/aer_fifo/runs",
    "trial-03-signoff": "hw/openlane/aer_fifo/runs",
    "sky-14-6x2-rcmodel": "hw/openlane/pilot_sky130/runs",
}

# relative to the run directory -> name under docs/evidence/<tag>/
WANTED = {
    "final/metrics.json": "metrics.json",
    "resolved.json": "resolved.json",
}

README = """<!--
SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
SPDX-License-Identifier: CC-BY-4.0
-->
# Recorded evidence

Generated by `scripts/collect_evidence.py`. One directory per
place-and-route run that a document in this corpus cites, carrying the
two small files that make the run's own numbers checkable from a clone:

* `metrics.json` — what the flow reported: instance counts, utilisation,
  the slack at every corner, DRC and antenna counts, area.
* `resolved.json` — the configuration the run was actually given, after
  every default and override was resolved.

**This is a record, not a run.** Nothing here can be re-derived from
this repository: re-deriving it needs the PDK, the flow and hours of
compute. A test that reads these files reports *checked against the
recorded artefact*, which is a weaker claim than *checked*, and the
difference is deliberate.

**What is not here**: netlists, DEF, GDS, SPICE, reports, logs. They
are large and they stay in the gitignored `runs/` trees. Any claim that
needs one of them is still a skip, and the skip message names the
digest in `docs/80-artefact-digests.tsv` that the absent file would
have to match.

Every file here is hash-pinned in `docs/80-artefact-digests.tsv`, so a
silently edited metric fails a test rather than travelling.

| run | flow | cited for |
|---|---|---|
"""

CITED = {
    "full3": "the first whole-SoC layout",
    "npu2": "the accelerator's own layout",
    "s71boot": "the boot-hardened six-macro layout",
    "s77gate": "the gate-level clock-gating run",
    "s81ptd": "the power and timing-derate study",
    "s83romecc5": "the eight-macro sign-off layout",
    "s83ant": "the antenna-repair variant of the sign-off",
    "s83lvsbb2": "the LVS run with the vendor macros black-boxed",
    "signoff-6x2": "the pilot sign-off",
    "signoff-6x2-gated": "the pilot sign-off with the checkers bound",
    "submission-6x2": "the shuttle submission",
    "submission-6x2-gated": "the shuttle submission with the checkers bound",
    "g0gates2": "ROADMAP gate G0's evidence run",
    "trial-03-signoff": "the earlier AER FIFO sign-off",
    "sky-14-6x2-rcmodel": "the Sky130 cross-check",
}


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def collect(check):
    missing, copied, changed = [], [], []
    rows = []
    for tag, base in sorted(RUNS.items()):
        src_dir = ROOT / base / tag
        rows.append("| `%s` | `%s` | %s |" % (tag, base, CITED.get(tag, "")))
        for rel, name in WANTED.items():
            src = src_dir / rel
            dst = OUT / tag / name
            if not src.is_file():
                missing.append("%s/%s" % (tag, rel))
                continue
            if check:
                if not dst.is_file():
                    changed.append("%s/%s is not committed" % (tag, name))
                elif digest(src) != digest(dst):
                    changed.append("%s/%s differs from the run tree" % (tag, name))
                continue
            dst.parent.mkdir(parents=True, exist_ok=True)
            if not dst.is_file() or digest(src) != digest(dst):
                shutil.copyfile(src, dst)
                copied.append("%s/%s" % (tag, name))
    return missing, copied, changed, rows


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="compare rather than copy; exit 1 on a difference")
    a = ap.parse_args()

    missing, copied, changed, rows = collect(a.check)

    if a.check:
        for m in missing:
            print("  run tree absent, nothing to compare: %s" % m)
        for c in changed:
            print("  DIFFERS: %s" % c)
        print("  %d evidence files differ from their run trees" % len(changed))
        return 1 if changed else 0

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "README.md").write_text(README + "\n".join(rows) + "\n",
                                   encoding="utf-8")
    for m in missing:
        print("  run tree absent, not collected: %s" % m)
    for c in copied:
        print("  collected %s" % c)
    have = sorted(p for p in OUT.rglob("*.json"))
    total = sum(p.stat().st_size for p in have)
    print("  %d files under docs/evidence, %.1f kB" % (len(have), total / 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
