#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
"""Generate a structural IHP chip shell from the reviewed full-core pin contract.

This creates actual I/O cell instances and read-only MBIST access. It does not
place/route pads, provide PCIe analog pins, select a package or qualify ESD/SI.
The caller must compare the contract against the actual selected core netlist.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / 'hw/soc/chip-io-contract.json'


def generate(contract):
    ports = contract['core_ports']
    consumed = set()
    pads, instances, manifest = [], [], []
    power = '.iovdd(IOVDD), .iovss(IOVSS), .vdd(VDD), .vss(VSS)'

    def bit(name, i):
        return name if ports[name]['width'] == 1 else f'{name}[{i}]'

    def pad(name, width, master, signals):
        pads.append(f'    inout wire {"" if width == 1 else f"[{width-1}:0] "}{name}')
        for i in range(width):
            pn = name if width == 1 else f'{name}[{i}]'
            suffix = '' if width == 1 else f'_{i}'
            pins = [f'.pad({pn})', power]
            for pin, net in signals.items():
                value = net if net.startswith("1'") else bit(net, i)
                pins.append(f'.{pin}({value})')
            instance = f'u_{name}{suffix}'
            instances.append(f'    {master} {instance} ({", ".join(pins)});')
            manifest.append(dict(instance=instance, master=master, pad=pn))

    for entry in contract['bidirectional']:
        inputs = [entry['input'], entry['enable']]
        if entry.get('output'):
            inputs.append(entry['output'])
        width = ports[entry['input']]['width']
        if any(n in consumed or ports[n]['width'] != width for n in inputs):
            raise ValueError('Duplicate or inconsistent bidirectional pin')
        if ports[inputs[0]]['direction'] != 'input' or any(
            ports[n]['direction'] != 'output' for n in inputs[1:]
        ):
            raise ValueError('Bidirectional pin direction mismatch')
        consumed.update(inputs)
        pad(entry['pad'], width, 'sg13g2_IOPadInOut4mA',
            dict(p2c=entry['input'], c2p=entry.get('output', "1'b0"), c2p_en=entry['enable']))

    fields = contract['status_lsb_first']
    width = 0
    for field in fields:
        n = field['port']
        if n in consumed or ports[n]['direction'] != 'output':
            raise ValueError('Invalid status pin')
        field_width = ports[n]['width']
        if field['lsb'] != width:
            raise ValueError('Noncontiguous status frame')
        width += field_width
        consumed.add(n)
    if width != 159:
        raise ValueError('Unexpected MBIST payload width')
    for n, p in ports.items():
        if n in consumed:
            continue
        if p['direction'] not in ('input', 'output') or p['width'] < 1:
            raise ValueError('Unsupported core port')
        pad('pad_' + n, p['width'], 'sg13g2_IOPadIn' if p['direction'] == 'input'
            else 'sg13g2_IOPadOut4mA', {'p2c' if p['direction'] == 'input' else 'c2p': n})
        consumed.add(n)
    assert consumed == set(ports)
    # Local test wires join the same pad construction path, without inventing
    # ports on the fixed core. All four pins are dedicated read-only access.
    for n, direction in [('test_clk', 'input'), ('test_req', 'input'),
                         ('test_ready', 'output'), ('test_data', 'output')]:
        ports = {**ports, n: dict(width=1, direction=direction)}
        pad('pad_' + n, 1, 'sg13g2_IOPadIn' if direction == 'input'
            else 'sg13g2_IOPadOut4mA', {'p2c' if direction == 'input' else 'c2p': n})
    # REUSE-IgnoreStart
    decl = ['// SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut',
            '// SPDX-License-Identifier: CERN-OHL-W-2.0',
            '// Generated by scripts/generate_chip_io.py; do not edit.',
            '// Requires the selected parameter-resolved mapped soc_top, not RTL defaults.',
            '`default_nettype none', 'module nssoc_chip (',
            ',\n'.join(['    inout wire VDD, VSS, IOVDD, IOVSS'] + pads), ');']
    # REUSE-IgnoreEnd
    for n, p in ports.items():
        bus = "" if p["width"] == 1 else "[{}:0] ".format(p["width"] - 1)
        decl.append(f'    wire {bus}{n};')
    decl += ['    wire [191:0] status_frame;',
             '    assign status_frame = {32\'h4d420001, 1\'b0, ' +
             ', '.join(f['port'] for f in reversed(fields)) + '};',
             '    soc_status_serial u_status (.clk_i(clk_i), .rst_ni(rst_ni),',
             '        .status_i(status_frame), .test_clk_i(test_clk), .test_req_i(test_req),',
             '        .test_ready_o(test_ready), .test_data_o(test_data));',
             '    soc_top u_core (',
             ',\n'.join(f'        .{n}({n})' for n in contract['core_ports']), '    );']
    for supply in ('Vdd', 'Vss', 'IOVdd', 'IOVss'):
        master = 'sg13g2_IOPad' + supply
        instances.append(f'    {master} u_supply_{supply} ({power});')
        manifest.append(dict(instance='u_supply_' + supply, master=master, supply=True))
    decl += instances + ['endmodule', '`default_nettype wire', '']
    return '\n'.join(decl), manifest


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--output', type=Path, required=True)
    ap.add_argument('--core-json', type=Path, required=True,
                    help='Yosys JSON of the selected mapped soc_top; required port check')
    args = ap.parse_args()
    if args.output.exists():
        ap.error('Refusing to replace an existing output directory')
    contract = json.loads(CONTRACT.read_text())
    actual = json.loads(args.core_json.read_text())['modules']['soc_top']['ports']
    signature = {n: dict(direction=p['direction'], width=len(p['bits']))
                 for n, p in actual.items()}
    if signature != contract['core_ports']:
        ap.error('Selected core differs from the reviewed pin contract')
    text, cells = generate(contract)
    args.output.mkdir(parents=True)
    (args.output / 'nssoc_chip.v').write_text(text)
    (args.output / 'pads.json').write_text(json.dumps(cells, indent=2) + '\n')
    inputs = [args.core_json.resolve(), CONTRACT, Path(__file__).resolve()]
    metadata = dict(scope='Structural mapped-core shell only; physical routing and qualification pending.',
                    input_sha256={str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in inputs},
                    signal_pads=sum(not c.get('supply', False) for c in cells), supply_pads=4)
    (args.output / 'manifest.json').write_text(json.dumps(metadata, indent=2) + '\n')


if __name__ == '__main__':
    main()
