#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0
"""Render the current tracked-path counts without rewriting historical claims."""
import argparse
from collections import Counter
from pathlib import Path
import subprocess

import spdx_check

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- BEGIN GENERATED LICENCE INVENTORY -->'
END = '<!-- END GENERATED LICENCE INVENTORY -->'


def render():
    paths = subprocess.check_output(['git', 'ls-files', '-z'], cwd=ROOT).decode().split('\0')
    paths = [p for p in paths if p]
    counts = Counter(p.split('/')[0] + '/' if '/' in p else 'root files' for p in paths)
    inline = sum(spdx_check.classify(p)[1] is not None for p in paths)
    lines = [START, f'{len(paths)} tracked files: {inline} with inline tags and '
             f'{len(paths)-inline} covered by path.', '',
             'Generated by `python3 scripts/licence_inventory.py --write`; checked with',
             '`python3 scripts/licence_inventory.py --check`. Licence expressions and',
             'third-party notices are governed by `REUSE.toml` and `reuse lint`, not',
             'inferred from these counts.', '', '| Path | Tracked files |', '|---|---:|']
    lines += [f'| `{path}` | {count} |' for path, count in sorted(counts.items())]
    return '\n'.join(lines + [END])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'LICENSES.md'
    text = path.read_text()
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit('Expected exactly one inventory marker pair')
    a, z = text.index(START), text.index(END) + len(END)
    new = text[:a] + render() + text[z:]
    if args.write:
        path.write_text(new)
    elif new != text:
        raise SystemExit('Tracked-path inventory stale; run scripts/licence_inventory.py --write')
    print('Tracked-path licence inventory matches Git')


if __name__ == '__main__':
    main()
