#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

"""Check -- and, with --apply, insert -- the SPDX header on every source file.

This script is the licence policy of `docs/14-licensing-decision.md`
section 6.4 in machine-readable form. The document says what the licence
set is; this file is what makes the claim true of the tree rather than
asserted about it, which is the same standard `hw/openlane/checker_audit.py`
applies to the flow's own gates.

    python3 scripts/spdx_check.py            report, exit 1 if anything is wrong
    python3 scripts/spdx_check.py --apply    insert the missing headers
    python3 scripts/spdx_check.py --list     print the classification of every file

WHAT IS TAGGED INLINE, AND WHAT IS NOT

A file is tagged inline when it is a SOURCE FILE and its syntax has a
comment. Everything else is covered by path, in `.reuse/dep5` and
`LICENSES.md`, and this script checks that those two agree with the
classification below -- so a file that cannot carry a tag is still
covered by a rule, not by silence.

Four groups are deliberately NOT tagged inline, each for a stated reason:

  tt/**            regenerated by scripts/gen_tt_submission.py from
                   hw/rtl/ and from the upstream Tiny Tapeout template.
                   The Verilog under tt/src/ is byte-identical to
                   hw/rtl/ by `docs/34` section 2.3 and carries its tag
                   from there; the scaffolding stays Apache-2.0 as
                   received. Editing tt/ by hand would break both.
  *.json           has no comment syntax, and six of them are pinned by
                   sha256 inside hw/openlane/pilot_ihp/mkconfig.py
                   (`docs/34` section 5.1). A header would void a freeze.
  *.md *.csv *.tsv documents and measurement data. CC-BY-4.0 by path.
                   The documents are not tagged because `docs/00-index.md`
                   and `sw/tests/test_doc_links.py` parse the first line
                   of every document, and a licence header is not worth
                   a parser change.
  two ISC files    hw/soc/rvformal/insns/insn_div.v and insn_rem.v are
                   corrected copies of riscv-formal's models and carry
                   upstream's ISC notice inline (`docs/14` section 2.1).
                   This script checks they still say ISC.

GENERATED FILES carry the header because their GENERATOR emits it. They
are checked here like any other file; if one fails, re-run its
generator rather than editing it.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COPYRIGHT = "SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut"

HW = "CERN-OHL-W-2.0"   # RTL, testbenches, constraints, formal jobs
SW = "Apache-2.0"       # generators, golden models, harnesses, flow drivers, CI
DOC = "CC-BY-4.0"       # documents and measurement data

# Files that carry a licence that is not this project's to choose.
THIRD_PARTY = {
    "hw/soc/rvformal/insns/insn_div.v": "ISC",
    "hw/soc/rvformal/insns/insn_rem.v": "ISC",
}

# Path prefixes covered by .reuse/dep5 instead of an inline tag.
UNTAGGED_PREFIXES = ("tt/", "LICENSES/", ".reuse/")
UNTAGGED_SUFFIXES = (".json", ".md", ".csv", ".tsv", ".sha256", ".svg",
                     ".gitignore", ".txt", ".ini")
UNTAGGED_NAMES = {"LICENSE", "pytest.ini", ".gitignore"}

# Comment syntax by suffix. The value is (prefix, suffix); a suffix of ""
# means a line comment.
HASH = ("# ", "")
SLASH = ("// ", "")
BLOCK = ("/* ", " */")
PCT = ("% ", "")

SYNTAX = {
    ".v": SLASH, ".vh": SLASH, ".sv": SLASH, ".c": SLASH, ".h": SLASH,
    ".S": SLASH, ".ld": BLOCK,
    ".sdc": HASH, ".sby": HASH, ".tcl": HASH, ".py": HASH, ".sh": HASH,
    ".mk": HASH, ".yml": HASH, ".yaml": HASH, ".awk": HASH, ".cfg": HASH,
    ".ys": HASH,
    ".tex": PCT, ".bib": PCT,
}

# Directories where the class of a file is decided by what the directory
# is FOR, not by the file's extension. `paper/` holds a document, its
# bibliography and the registry of the numbers the document prints; all
# three are the document, and `docs/14` section 6.4 puts documents and
# their data under CC-BY-4.0. The Python that re-derives those numbers is
# a program and stays Apache-2.0, because it is the kind of thing section
# 6.5 wants to be able to offer upstream.
# paper-residual/ joined it 2026-09-14: a second paper, same three
# kinds of file, same reason.
# thesis/ joined on 2026-09-16, the day the checker first went red on it.
# Its .tex and .bib are the sources of a DOCUMENT and carry CC-BY-4.0 by
# docs/14 section 6.4, exactly as the three preprint directories do; the
# extension map alone would call them Apache-2.0 and did.
DIR_IS_DOCUMENT = ("paper/", "paper-residual/", "paper-design/", "thesis/")
DOCUMENT_SUFFIXES = {".tex", ".bib", ".yaml", ".yml", ".csv", ".tsv"}

# Hardware sources take CERN-OHL-W-2.0; everything else executable takes
# Apache-2.0. The boundary is `docs/14` section 6.5: tooling is permissive
# so that it can be offered upstream to yosys, LibreLane and IHP-Open-PDK,
# none of which takes reciprocal code.
HW_SUFFIXES = {".v", ".vh", ".sv", ".sdc", ".sby", ".tcl", ".ys"}


def strip_template(name):
    """foo.sdc.in -> .sdc; foo.py -> .py; Makefile.fi -> (Makefile)."""
    if name.startswith("Makefile"):
        return ".mk"
    parts = name.split(".")
    if len(parts) >= 3 and parts[-1] == "in":
        return "." + parts[-2]
    if len(parts) >= 2:
        return "." + parts[-1]
    return ""


def classify(rel):
    """Return (licence, syntax) or (licence, None) for path-covered files."""
    if rel in THIRD_PARTY:
        return THIRD_PARTY[rel], SYNTAX.get(strip_template(Path(rel).name))
    name = Path(rel).name
    if rel.startswith(UNTAGGED_PREFIXES):
        return None, None
    if name in UNTAGGED_NAMES or (rel.endswith(UNTAGGED_SUFFIXES)
                                  and not name.startswith("Makefile")):
        return None, None
    suf = strip_template(name)
    syn = SYNTAX.get(suf)
    if syn is None:
        return None, None
    if rel.startswith(DIR_IS_DOCUMENT) and suf in DOCUMENT_SUFFIXES:
        return DOC, syn
    lic = HW if suf in HW_SUFFIXES else SW
    return lic, syn


def path_licence(rel):
    """The licence a path-covered (untagged) file is under, for LICENSES.md."""
    if rel.startswith("tt/"):
        return "see tt/README.md"
    if rel.startswith(DIR_IS_DOCUMENT):
        return DOC
    if rel.endswith((".md", ".csv", ".tsv")):
        return DOC
    if rel.endswith(".json"):
        return HW if rel.startswith(("hw/", "formal/", "tt/")) else SW
    return SW


TAG_RE = re.compile(r"SPDX-License-Identifier:\s*([A-Za-z0-9.\-+]+)")
COMMENT_START = ("#", "//", "/*", "*", "--", ";", "%")

# How far into a file a tag may sit and still count. A header is a
# header: after a shebang, before the code.
HEADER_LINES = 12


def read_tag(text):
    """The tag, if this file carries one in its header COMMENT.

    NARROWED 2026-09-09, and the reason is that the first version of this
    function reported this very file as tagged when it was not. It
    searched the first 4000 characters for the identifier string with no
    regard for where or what it was, and this file's own docstring and
    regular expression both contain that string -- so the checker read
    its own prose as its own licence. It went unnoticed until an edit
    pushed the docstring past 4000 characters and the file suddenly
    turned up MISSING.

    That is the failure shape this corpus names most often: a check that
    passed, read wider than what it actually looked at. A tag now counts
    only on a COMMENT LINE inside the first {n} lines, which is where a
    header is and where prose about headers is not.
    """.format(n=HEADER_LINES)
    for line in text.split("\n")[:HEADER_LINES]:
        s = line.strip()
        if not s.startswith(COMMENT_START):
            continue
        m = TAG_RE.search(s)
        if m:
            return m.group(1).strip()
    return None


def header_lines(lic, syn):
    pre, post = syn
    return [f"{pre}{COPYRIGHT}{post}", f"{pre}SPDX-License-Identifier: {lic}{post}"]


def insert(text, lic, syn):
    lines = text.split("\n")
    at = 0
    # After a shebang, and after a `//` line that a tool requires first.
    if lines and lines[0].startswith("#!"):
        at = 1
    block = header_lines(lic, syn)
    # A blank line after the header, unless the file already starts blank.
    tail = lines[at:]
    if tail and tail[0].strip():
        block = block + [""]
    return "\n".join(lines[:at] + block + tail)


def tracked():
    """Every file to classify.

    `git ls-files` when this is a checkout, and a filesystem walk when it
    is not -- a generated mirror is a plain directory until it is
    committed, and a check that cannot run there is a check that does not
    run where it is most needed.
    """
    # --others --exclude-standard as well as --cached, so a file is
    # checked the moment it exists rather than the moment it is staged.
    # WIDENED 2026-09-09 after this check reported a clean tree while
    # three files it should have rejected sat untracked beside it: the
    # policy was run, then the files were added, then they were
    # committed, and nothing between those steps looked. A check whose
    # scope is narrower than the thing it certifies is the shape this
    # project keeps finding, and it found it here in its own licence
    # gate.
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT, capture_output=True, text=True)
    if out.returncode == 0 and out.stdout.strip():
        return sorted({l for l in out.stdout.split("\n") if l})
    skip = {".git", "__pycache__", ".venv", "ext", "tools", "gen", "genrvfi",
            "runs", "out", "_site", "node_modules"}
    found = []
    for p in ROOT.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        if any(part in skip for part in rel.parts):
            continue
        found.append(str(rel))
    return sorted(found)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    missing, wrong, ok, covered = [], [], 0, 0
    for rel in tracked():
        lic, syn = classify(rel)
        p = ROOT / rel
        if lic is None or syn is None:
            covered += 1
            if args.list:
                print(f"{'path':<18} {path_licence(rel):<18} {rel}")
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            covered += 1
            continue
        have = read_tag(text)
        if args.list:
            print(f"{'inline':<18} {lic:<18} {rel}")
        if have is None:
            if args.apply and rel not in THIRD_PARTY:
                p.write_text(insert(text, lic, syn), encoding="utf-8")
                ok += 1
            else:
                missing.append((rel, lic))
        elif have != lic:
            wrong.append((rel, have, lic))
        else:
            ok += 1

    if args.list:
        return 0

    for rel, lic in missing:
        print(f"MISSING  {lic:<18} {rel}")
    for rel, have, lic in wrong:
        print(f"WRONG    got {have}, expected {lic}: {rel}")
    print(f"\n{ok} tagged, {covered} covered by path, "
          f"{len(missing)} missing, {len(wrong)} wrong")
    return 1 if (missing or wrong) else 0


if __name__ == "__main__":
    sys.exit(main())
