"""Self-contained smoke test for the Tiny Tapeout submission.

GENERATED by scripts/gen_tt_submission.py in the neuromorphic-space-soc
repository. Do not edit here; edit the source repository and regenerate.

This file deliberately does NOT import the source repository's golden
model: a submission repository has to be testable on its own, and the
Tiny Tapeout `test` workflow checks out nothing else. What it covers is
the part that a broken port map, a broken pin contract or a broken host
protocol would break, and that a datasheet reader would hit first:

  * reset leaves uio_oe at 0xF0 and every fault pin quiescent
  * the identity register reads back over the serial port
  * a write/read round trip through SCRATCH
  * the read-only rule (a write to VERSION changes nothing)
  * an end-to-end event: weights loaded through the SECDED codec, one
    SPIKE strobed in on the AER pins, the neuron id read off uio[7:4],
    and the pin-side acknowledge retiring the entry

The full regression - bit-exact inference against a Python reference
model, the SECDED syndrome walk, the double-bit E10 substitution, the
scrub loop and the TMR masking proof - lives in the source repository
and runs against this same port list.
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

CLK_NS = 20          # 50 MHz, the clock_hz in info.yaml
HALF = 2 * CLK_NS    # serial half period, i.e. SER_SCK = clk/4, the limit

# ui_in bit positions
SER_SCK, SER_CS_N, SER_MOSI = 0, 1, 2
AER_IN_STB, AER_IN_TICK, AER_OUT_ACK, SCRUB_STB = 3, 4, 5, 6
# uo_out bit positions
SER_MISO, BUSY, AER_IN_RDY, AER_OUT_VLD = 0, 1, 2, 3
ERR, SEC, DED, TMR = 4, 5, 6, 7

ADDR_ID = 0x000
ADDR_VERSION = 0x004
ADDR_SCRATCH = 0x008
ADDR_CTRL = 0x00C
ADDR_STATUS = 0x010
ADDR_CFG_NEUR = 0x020
ADDR_CFG_AXON = 0x024
ADDR_CFG_THRESH = 0x028
ADDR_CFG_SYNSHIFT = 0x034
ADDR_CFG_FLAGS = 0x03C
ADDR_W_ADDR = 0x050
ADDR_W_DATA_LO = 0x054
ADDR_W_DATA_HI = 0x058

ID_VALUE = 0x4E505531        # ASCII "NPU1"
CTRL_EN, CTRL_STATE_CLR = 1, 2
ST_BUSY, ST_OUT_EMPTY = 1 << 0, 1 << 2


class Pins:
    """Python-side shadow of the input pins.

    cocotb value deposits are scheduled, not immediate: a
    read-modify-write of dut.ui_in.value with no await in between reads
    the pre-deposit value and silently drops the previous bit write. Keep
    the shadow and only ever write the whole word.
    """

    def __init__(self, dut):
        self.dut = dut
        self.ui = 1 << SER_CS_N      # CS_N idles high, everything else low
        self.uio = 0

    def set_ui(self, bit, val):
        self.ui = (self.ui & ~(1 << bit)) | ((val & 1) << bit)
        self.dut.ui_in.value = self.ui

    def set_uio(self, val):
        self.uio = val & 0x0F
        self.dut.uio_in.value = self.uio


def uo(dut, bit):
    """X-safe single-bit sample of uo_out."""
    s = str(dut.uo_out.value)
    return 1 if s[7 - bit] == "1" else 0


def uio_out_nibble(dut):
    """uio_out[7:4], the emitted neuron id."""
    s = str(dut.uio_out.value)
    return int("".join("1" if c == "1" else "0" for c in s[:4]), 2)


async def spi_byte(p, tx):
    """One mode-0 byte, MSB first. Returns the byte shifted out on MISO.

    MISO is sampled just after the rising edge, which is where a mode-0
    master samples it; the slave changes it on the falling edge.
    """
    rx = 0
    for i in range(7, -1, -1):
        p.set_ui(SER_MOSI, (tx >> i) & 1)
        await Timer(HALF, unit="ns")
        p.set_ui(SER_SCK, 1)
        await Timer(1, unit="ns")
        rx = (rx << 1) | uo(p.dut, SER_MISO)
        await Timer(HALF - 1, unit="ns")
        p.set_ui(SER_SCK, 0)
    return rx


async def frame(p, write, addr, data=0):
    """One 40-bit frame: command byte then 32 data bits.

    The leading and trailing chip-select gaps are one full SER_SCK period
    each. Both are host obligations, not politeness: the frame reset has
    to clear the two-flop synchronizer before the first sampled clock
    edge, and the deselect has to be seen before the next frame starts or
    the bit counter carries over and the next frame decodes at the wrong
    offset.
    """
    p.set_ui(SER_CS_N, 0)
    await Timer(2 * HALF, unit="ns")
    await spi_byte(p, ((1 if write else 0) << 7) | ((addr >> 2) & 0x7F))
    out = 0
    for shift in (24, 16, 8, 0):
        out = (out << 8) | await spi_byte(p, (data >> shift) & 0xFF)
    await Timer(HALF, unit="ns")
    p.set_ui(SER_CS_N, 1)
    await Timer(2 * HALF, unit="ns")
    return out


async def rd(p, addr):
    return await frame(p, False, addr)


async def wr(p, addr, data):
    await frame(p, True, addr, data)


async def reset(dut):
    """Bring the DUT up. Returns the pin shadow used by every helper."""
    p = Pins(dut)
    cocotb.start_soon(Clock(dut.clk, CLK_NS, unit="ns").start())
    dut.ena.value = 1
    dut.ui_in.value = p.ui
    dut.uio_in.value = p.uio
    dut.rst_n.value = 0
    for _ in range(6):
        await RisingEdge(dut.clk)
    dut.rst_n.value = 1
    for _ in range(6):
        await RisingEdge(dut.clk)
    return p


@cocotb.test()
async def test_reset_state(dut):
    """After reset the direction word is fixed and no pin is asserted."""
    p = await reset(dut)

    assert int(dut.uio_oe.value) == 0xF0, (
        "uio_oe must be 0xF0 (uio[3:0] in, uio[7:4] out), got "
        + str(dut.uio_oe.value)
    )
    for name, bit in (("BUSY", BUSY), ("AER_OUT_VLD", AER_OUT_VLD),
                      ("ERR", ERR), ("SEC", SEC), ("DED", DED), ("TMR", TMR)):
        assert uo(dut, bit) == 0, name + " asserted after reset"
    assert uo(dut, AER_IN_RDY) == 1, "input queue not ready after reset"
    assert p.ui & (1 << SER_CS_N), "the testbench must idle CS_N high"


@cocotb.test()
async def test_identity(dut):
    """The identity register is the first thing a bench reads."""
    p = await reset(dut)
    got = await rd(p, ADDR_ID)
    assert got == ID_VALUE, "ID: expected %#010x, got %#010x" % (ID_VALUE, got)


@cocotb.test()
async def test_scratch_round_trip(dut):
    """Write and read back, which exercises both frame directions."""
    p = await reset(dut)
    for value in (0xA5A5_5A5A, 0x0000_0001, 0xFFFF_FFFF, 0x0000_0000):
        await wr(p, ADDR_SCRATCH, value)
        got = await rd(p, ADDR_SCRATCH)
        assert got == value, (
            "SCRATCH: wrote %#010x, read %#010x" % (value, got)
        )


@cocotb.test()
async def test_read_only_register_rejects_writes(dut):
    """A write to a read-only register must not change it."""
    p = await reset(dut)
    before = await rd(p, ADDR_VERSION)
    await wr(p, ADDR_VERSION, 0xDEAD_BEEF)
    after = await rd(p, ADDR_VERSION)
    assert after == before, (
        "VERSION changed from %#010x to %#010x on a write" % (before, after)
    )


@cocotb.test()
async def test_spike_in_and_out_on_the_pins(dut):
    """One event, end to end, without touching the serial event queues.

    Weights go in through the SECDED encoder, the SPIKE is strobed in on
    the AER pins, the emitted neuron id is read off uio[7:4], and the
    pin-side acknowledge retires it. That is the whole pin contract in
    one test.
    """
    p = await reset(dut)

    # Follow the elaborated geometry rather than assuming it.
    n_neurons = await rd(p, ADDR_CFG_NEUR)
    n_axons = await rd(p, ADDR_CFG_AXON)
    assert 4 <= n_neurons <= 16 and 4 <= n_axons <= 16, (
        "implausible geometry read back: %d neurons, %d axons"
        % (n_neurons, n_axons)
    )

    await wr(p, ADDR_CTRL, CTRL_STATE_CLR)
    for _ in range(4):
        if (await rd(p, ADDR_STATUS)) & ST_BUSY == 0:
            break
    else:
        raise AssertionError("STATE_CLR never completed")

    await wr(p, ADDR_CFG_THRESH, 1)
    await wr(p, ADDR_CFG_SYNSHIFT, 0)
    await wr(p, ADDR_CFG_FLAGS, 0)

    # Only axon 1 drives neuron 2, and it drives it over threshold.
    # Weights are axon-major, 16 four-bit weights per 64-bit word, weight
    # k of a word at bits [4k+3:4k].
    flat = [0] * (n_axons * n_neurons)
    flat[1 * n_neurons + 2] = 7
    await wr(p, ADDR_W_ADDR, 0)
    for base in range(0, len(flat), 16):
        word = 0
        for k, weight in enumerate(flat[base:base + 16]):
            word |= (weight & 0xF) << (4 * k)
        await wr(p, ADDR_W_DATA_LO, word & 0xFFFFFFFF)
        await wr(p, ADDR_W_DATA_HI, (word >> 32) & 0xFFFFFFFF)

    await wr(p, ADDR_CTRL, CTRL_EN)
    assert uo(dut, AER_IN_RDY) == 1, "input queue not ready before the spike"

    p.set_uio(1)                 # axon id 1
    p.set_ui(AER_IN_TICK, 0)     # SPIKE, not TICK
    for _ in range(4):
        await RisingEdge(dut.clk)
    p.set_ui(AER_IN_STB, 1)
    for _ in range(4):
        await RisingEdge(dut.clk)
    p.set_ui(AER_IN_STB, 0)

    for _ in range(200):
        await RisingEdge(dut.clk)
        if uo(dut, AER_OUT_VLD):
            break
    else:
        raise AssertionError("AER_OUT_VLD never asserted after a SPIKE")
    assert uio_out_nibble(dut) == 2, (
        "AER_OUT_ID must carry neuron id 2, got %d" % uio_out_nibble(dut)
    )

    p.set_ui(AER_OUT_ACK, 1)
    for _ in range(6):
        await RisingEdge(dut.clk)
    p.set_ui(AER_OUT_ACK, 0)
    for _ in range(6):
        await RisingEdge(dut.clk)
    assert uo(dut, AER_OUT_VLD) == 0, "the pin acknowledge must retire the event"
    assert (await rd(p, ADDR_STATUS)) & ST_OUT_EMPTY, "output queue not empty"

    # Nothing in this test should have tripped a fault pin.
    for name, bit in (("ERR", ERR), ("SEC", SEC), ("DED", DED), ("TMR", TMR)):
        assert uo(dut, bit) == 0, name + " asserted during a clean run"
