# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

# Generated by regmap/generate_peripherals.py; edit the YAML files in regmap/peripherals.

BOOT = {'BSTRAP': 0, 'BSTAT': 4, 'BRPT': 8, 'EPOCH': 12, 'CRASH': 16}

BUSSTAT = {'STATUS': 0, 'IRQEN': 4, 'RFSEC': 8, 'RFRD': 12, 'RFDED': 16, 'TMRERR': 20, 'CLR': 24, 'NPUCOR': 28, 'NPUDET': 32, 'NPUTMR': 36, 'MTECC': 40, 'APBTO': 44}

CLINT = {'MSIP': 0, 'MTIMECMPL': 16384, 'MTIMECMPH': 16388, 'MTIMEL': 49144, 'MTIMEH': 49148}

ETH = {'CTRL': 0, 'STATUS': 4, 'TX': 8, 'RX': 12, 'EVENTS': 16, 'IRQEN': 20, 'MDIO': 24, 'ID': 252}

GPIO = {'DATA': 0, 'OUTPUT': 4, 'DIR': 8, 'IMASK': 12, 'IPOL': 16, 'IEDGE': 20, 'BYPASS': 24, 'CAP': 28, 'IAVAIL': 64, 'IFLAG': 68, 'OUTPUT_OR': 84, 'DIR_OR': 88, 'IMASK_OR': 92, 'OUTPUT_AND': 100, 'DIR_AND': 104, 'IMASK_AND': 108, 'OUTPUT_XOR': 116, 'DIR_XOR': 120, 'IMASK_XOR': 124}

I2C = {'STATUS': 0, 'PRESCALE': 4, 'ADDRESS': 8, 'COMMAND': 12, 'DATA': 16, 'IRQEN': 20, 'EVENTS': 24, 'TIMEOUT': 28}

NPUCFG = {'ID': 0, 'VERSION': 4, 'CTRL': 8, 'STATUS': 12, 'IRQCAUSE': 16, 'IRQMASK': 20, 'EVQ_IN': 24, 'EVQ_OUT': 28, 'EVQ_STAT': 32, 'GEOM': 36, 'CNT': 40, 'CNT_DROP': 44}

QSPI = {'CONF': 0, 'CTRL': 4, 'STAT': 8, 'RX': 12, 'TX': 16, 'CMD': 20, 'ADDR': 24}

SCRUB = {'STATUS': 0, 'IRQEN': 4, 'RAMSEC': 8, 'RAMRD': 12, 'RAMDED': 16, 'ROMSEC': 20, 'ROMRD': 24, 'ROMDED': 28, 'CLR': 32, 'CTRL': 36, 'RAMADDR': 40, 'ROMADDR': 44}

SPI = {'CTRL': 0, 'DIV': 4, 'DATA': 8, 'STATUS': 12}

SPW = {'CTRL': 0, 'STATUS': 4, 'DIV': 8, 'TX': 12, 'RX': 16, 'IRQEN': 20, 'EVENTS': 24, 'TIME_TX': 28, 'TIME_RX': 32}

UART = {'DATA': 0, 'STATUS': 4, 'CTRL': 8, 'SCALER': 12}
