# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

"""Bit-exact golden model of the weight-SRAM SECDED code (72, 64).

Normative source: docs/10-npu-mvp-spec.md section 5 ("64 data bits = 16
weights, plus 8 SECDED check bits (72-bit macro word, 12.5 percent
overhead)") and section 11.2 / equation E10 (single-bit corrected inline
with CNT_SEC, double-bit detected, uncorrectable word substituted with
zero contributions, processing continues). docs/09-formal-verification-plan.md
target #2 states the acceptance criteria proven over this code in
formal/secded.sby.

Plain Python ints only, like sw/golden/lif_core.py: no numpy, no floats,
no hidden dtype promotion. Every operation is the bit operation the
hardware performs.

--------------------------------------------------------------------
Code construction (Hsiao SEC-DED, distance 4)
--------------------------------------------------------------------

Codeword layout, 72 bits::

    code[63:0]   data field   (data bit j at code bit j)
    code[71:64]  check field  (check bit i at code bit 64 + i)

The parity-check matrix H is 8 x 72. Column j (j in [0, 64)) is
``COLUMNS[j]``, an 8-bit integer whose bit i is 1 when data bit j
participates in check bit i. Column 64 + i is ``1 << i`` (the check
field is the identity block, so H has full rank 8 and syndrome == 0 holds
exactly for codewords).

The 64 data columns are chosen by the Hsiao rule - all distinct, all
nonzero, all of ODD weight:

  * data bits 0..55: every 8-bit vector of weight 3 (there are
    C(8,3) = 56), in ascending numeric order;
  * data bits 56..63: eight vectors of weight 5, namely the complements
    of {0x07, 0x0B, 0x0D, 0x0E, 0x70, 0xB0, 0xD0, 0xE0} in ascending
    numeric order. That seed set covers each of the 8 rows exactly three
    times, so the weight-5 columns cover each row exactly five times and
    every row of H ends up with the same weight 27 (26 data bits + its
    own check bit) - equal XOR-tree depth on all eight check bits.

Why odd weights matter (this is the whole SEC-DED argument):

  * one flipped bit  -> syndrome = that bit's column: nonzero, ODD parity,
    and unique because the 72 columns are distinct. Correctable.
  * two flipped bits -> syndrome = XOR of two distinct columns: nonzero
    (distinctness) and of EVEN parity (odd XOR odd). It can never be
    mistaken for a single-bit syndrome, so a double error is always
    detected and never miscorrected.
  * zero flipped bits -> syndrome 0.

Decode rules (normative for the RTL, hw/rtl/secded_dec.v):

    s == 0                                  -> clean, no flags
    s odd parity and s matches a column      -> single error, corrected,
                                                sec = 1
    otherwise (s != 0)                       -> uncorrectable, ded = 1,
                                                data passed through raw

The "otherwise" branch also covers odd-parity syndromes that match no
column (56 of the 128 odd 8-bit values are not columns; a triple error
can produce one). Those are reported uncorrectable rather than
miscorrected - a strictly safer choice than blind correction, and the
reason ``sec`` means "corrected", not merely "odd syndrome".

Distance: the code has minimum distance 4, so it corrects any 1-bit error
and detects any 2-bit error, but makes no claim about 3-bit errors beyond
the miscorrection guard above.
"""

DATA_BITS = 64
CHECK_BITS = 8
CODE_BITS = DATA_BITS + CHECK_BITS  # 72-bit physical word (spec section 5)
DATA_MASK = (1 << DATA_BITS) - 1
CHECK_MASK = (1 << CHECK_BITS) - 1
CODE_MASK = (1 << CODE_BITS) - 1

# H matrix, data columns. Generated by the rule documented above; frozen
# here as literals because hw/rtl/secded_enc.v and hw/rtl/secded_dec.v
# carry the same matrix as row masks and must not drift from it.
COLUMNS = (
    0x07, 0x0B, 0x0D, 0x0E, 0x13, 0x15, 0x16, 0x19,
    0x1A, 0x1C, 0x23, 0x25, 0x26, 0x29, 0x2A, 0x2C,
    0x31, 0x32, 0x34, 0x38, 0x43, 0x45, 0x46, 0x49,
    0x4A, 0x4C, 0x51, 0x52, 0x54, 0x58, 0x61, 0x62,
    0x64, 0x68, 0x70, 0x83, 0x85, 0x86, 0x89, 0x8A,
    0x8C, 0x91, 0x92, 0x94, 0x98, 0xA1, 0xA2, 0xA4,
    0xA8, 0xB0, 0xC1, 0xC2, 0xC4, 0xC8, 0xD0, 0xE0,
    0x1F, 0x2F, 0x4F, 0x8F, 0xF1, 0xF2, 0xF4, 0xF8,
)

# H matrix, check columns: the identity block.
CHECK_COLUMNS = tuple(1 << i for i in range(CHECK_BITS))

# Row view of the same matrix: ROW_MASKS[i] has bit j set when data bit j
# feeds check bit i. This is the form the RTL uses (one 64-bit XOR
# reduction per check bit) and is derived here so the two views cannot
# disagree.
ROW_MASKS = tuple(
    sum(1 << j for j, col in enumerate(COLUMNS) if (col >> i) & 1)
    for i in range(CHECK_BITS)
)


def _check_int(name, value):
    """Reject anything that is not a plain int (floats, bools, numpy)."""
    if type(value) is not int:
        raise TypeError(f"{name} must be a plain int, got {type(value).__name__}")
    return value


def _check_range(name, value, bits):
    _check_int(name, value)
    if not 0 <= value < (1 << bits):
        raise ValueError(f"{name} = {value} outside [0, 2**{bits})")
    return value


def parity(value: int) -> int:
    """XOR reduction of all set bits of a non-negative int."""
    _check_int("value", value)
    if value < 0:
        raise ValueError("parity() takes a non-negative int")
    return bin(value).count("1") & 1


def check_bits(data: int) -> int:
    """The 8 check bits of a 64-bit data word (encoder core)."""
    _check_range("data", data, DATA_BITS)
    c = 0
    for i in range(CHECK_BITS):
        c |= parity(data & ROW_MASKS[i]) << i
    return c


def encode(data: int) -> int:
    """Encode 64 data bits into the 72-bit codeword {check[7:0], data[63:0]}."""
    return (check_bits(data) << DATA_BITS) | _check_range("data", data, DATA_BITS)


def syndrome(code: int) -> int:
    """Syndrome of a received 72-bit word: H * code, 8 bits."""
    _check_range("code", code, CODE_BITS)
    data = code & DATA_MASK
    stored = (code >> DATA_BITS) & CHECK_MASK
    return check_bits(data) ^ stored


def column_of_bit(index: int) -> int:
    """H column of codeword bit `index` (0..63 data, 64..71 check)."""
    _check_int("index", index)
    if not 0 <= index < CODE_BITS:
        raise ValueError(f"index {index} outside [0, {CODE_BITS})")
    if index < DATA_BITS:
        return COLUMNS[index]
    return CHECK_COLUMNS[index - DATA_BITS]


# Reverse map: syndrome value -> codeword bit index it identifies.
_SYNDROME_TO_BIT = {column_of_bit(i): i for i in range(CODE_BITS)}


class DecodeResult:
    """Outcome of one SECDED decode, mirroring hw/rtl/secded_dec.v ports.

    data       corrected 64-bit data field (raw field when uncorrectable)
    sec        1 when a single-bit error was corrected (drives CNT_SEC)
    ded        1 when the word is uncorrectable (drives CNT_DED,
               STATUS.DED_SEEN, FAULT_ADDR, and E10 zero substitution)
    syndrome   the 8-bit syndrome, for observability
    err_index  corrected codeword bit index, or None when sec == 0
    """

    __slots__ = ("data", "sec", "ded", "syndrome", "err_index")

    def __init__(self, data, sec, ded, syndrome_value, err_index):
        self.data = data
        self.sec = sec
        self.ded = ded
        self.syndrome = syndrome_value
        self.err_index = err_index

    def __eq__(self, other):
        if not isinstance(other, DecodeResult):
            return NotImplemented
        return (self.data, self.sec, self.ded, self.syndrome, self.err_index) == (
            other.data, other.sec, other.ded, other.syndrome, other.err_index)

    def __repr__(self):
        return (f"DecodeResult(data=0x{self.data:016X}, sec={self.sec}, "
                f"ded={self.ded}, syndrome=0x{self.syndrome:02X}, "
                f"err_index={self.err_index})")


def decode(code: int) -> DecodeResult:
    """Decode a received 72-bit word (see the decode rules in the header)."""
    s = syndrome(code)
    data = code & DATA_MASK
    if s == 0:
        return DecodeResult(data, 0, 0, 0, None)
    if parity(s) == 1 and s in _SYNDROME_TO_BIT:
        index = _SYNDROME_TO_BIT[s]
        if index < DATA_BITS:
            data ^= 1 << index  # correct in the data field
        # a flipped check bit needs no data repair; the flag still fires
        return DecodeResult(data, 1, 0, s, index)
    return DecodeResult(data, 0, 1, s, None)


def flip(code: int, positions) -> int:
    """Inject bit flips into a 72-bit word (the ECC_INJ verification hook).

    positions is an iterable of codeword bit indices; repeated indices
    cancel, exactly as XOR-based injection does in hardware.
    """
    _check_range("code", code, CODE_BITS)
    mask = 0
    for p in positions:
        _check_int("position", p)
        if not 0 <= p < CODE_BITS:
            raise ValueError(f"position {p} outside [0, {CODE_BITS})")
        mask ^= 1 << p
    return code ^ mask


# ---------------------------------------------------------------------
# Clear-port bit assignments
# (regmap/regmap.yaml, docs/10 section 10, hw/rtl/npu_regbank.v)
# ---------------------------------------------------------------------
#
# Two different registers clear this block's state, and they are not
# interchangeable. FAULT_CLR at 0x88 clears the fault block (0x70..0x80);
# STATUS_CLR at 0x14 clears the sticky bits of STATUS (b3..b6), one of
# which is DED_SEEN. A driver that writes only FAULT_CLR leaves DED_SEEN
# set, which is the behaviour hw/rtl/npu_regbank.v implements.

# FAULT_CLR (0x88, W1C). regmap.yaml declares all five bits as named
# fields of the register, and that declaration is the source: one bit per
# fault-block register, in offset order from 0x70 upward, which is the
# convention hw/rtl/npu_regbank.v note C2 restates. The literals below
# are a second copy of positions the YAML owns, so
# sw/tests/test_regmap.py cross-checks every one of them against the
# generated field table -- a bit that moves, is renamed or is added in
# the YAML fails there rather than silently diverging here.
FAULT_CLR_CNT_SEC = 1 << 0          # 0x70
FAULT_CLR_CNT_DED = 1 << 1          # 0x74
FAULT_CLR_CNT_EVQ_OVF = 1 << 2      # 0x78, register bank only, not modelled here
FAULT_CLR_CNT_AXON_OOR = 1 << 3     # 0x7C, register bank only, not modelled here
FAULT_CLR_FAULT_ADDR = 1 << 4       # 0x80
FAULT_CLR_ALL = 0x1F                # every assigned bit; [31:5] are ignored

# STATUS_CLR (0x14, W1C): a clear mask positioned like STATUS itself, so
# the bit that clears STATUS.DED_SEEN is bit 5.
STATUS_DED_SEEN = 1 << 5


class EccCounters:
    """Model of the fault-counter block fed by the decoder.

    Register semantics from docs/10 section 10 (fault block) and 11.2:
    CNT_SEC counts corrected single-bit events, CNT_DED counts
    uncorrectable events, FAULT_ADDR latches the weight SRAM word index of
    the last DED, and STATUS.DED_SEEN is sticky. The counters are
    read-only 32-bit registers.

    Clearing is split across two registers and this model keeps them
    apart, because the hardware does:

      * ``fault_clr()`` models a write to FAULT_CLR (0x88): CNT_SEC,
        CNT_DED and FAULT_ADDR, selected by mask. It does NOT touch
        DED_SEEN - that bit lives in STATUS, not in the fault block.
      * ``status_clr()`` models a write to STATUS_CLR (0x14): the sticky
        STATUS bits, of which DED_SEEN is the one this block owns.
      * ``reset()`` models rst_n: everything back to its reset value.

    Saturation is a house convention, not a docs/10 statement: a wrapped
    fault counter would erase the fault record it exists to preserve, so
    both counters stop at their maximum (same rule as the aer_fifo drop
    counter). Width is a constructor argument so a narrower hardware
    counter can be modelled without changing this file.

    Out of scope here: the same-cycle race convention of
    hw/rtl/npu_regbank.v note C1 (a fault observed in the same cycle as
    its clear write survives the clear). That is a register-bank timing
    property with no meaning in a call-sequential model; it is verified in
    hw/tb/test_npu_regbank.py and in formal/npu_regbank.sby.
    """

    def __init__(self, width: int = 32):
        _check_int("width", width)
        if width < 1:
            raise ValueError("counter width must be >= 1")
        self.width = width
        self.max_count = (1 << width) - 1
        self.reset()

    def reset(self):
        """rst_n: every modelled register back to its reset value."""
        self.cnt_sec = 0
        self.cnt_ded = 0
        self.fault_addr = 0
        self.ded_seen = 0

    def fault_clr(self, mask: int = FAULT_CLR_ALL):
        """FAULT_CLR (0x88) write: clear the selected fault-block registers.

        DED_SEEN is deliberately untouched: it is STATUS bit 5 and is
        cleared by STATUS_CLR (0x14), not from here.
        """
        _check_range("mask", mask, 32)
        if mask & FAULT_CLR_CNT_SEC:
            self.cnt_sec = 0
        if mask & FAULT_CLR_CNT_DED:
            self.cnt_ded = 0
        if mask & FAULT_CLR_FAULT_ADDR:
            self.fault_addr = 0

    def status_clr(self, mask: int = STATUS_DED_SEEN):
        """STATUS_CLR (0x14) write: clear the sticky STATUS bits selected.

        Only DED_SEEN (bit 5) belongs to this block; the other sticky bits
        of STATUS live in the register bank and are ignored here. The
        counters and FAULT_ADDR are not affected.
        """
        _check_range("mask", mask, 32)
        if mask & STATUS_DED_SEEN:
            self.ded_seen = 0

    def observe(self, result: DecodeResult, word_index: int = 0):
        """Account one decode. word_index is the weight SRAM word index."""
        _check_int("word_index", word_index)
        if word_index < 0:
            raise ValueError("word_index must be non-negative")
        if result.sec and self.cnt_sec < self.max_count:
            self.cnt_sec += 1
        if result.ded:
            if self.cnt_ded < self.max_count:
                self.cnt_ded += 1
            self.fault_addr = word_index  # FAULT_ADDR latches the last DED
            self.ded_seen = 1  # STATUS.DED_SEEN, sticky
        return result
